/* AEO-verrijking (post-process op de HTML, NIET via build.js).
   Voegt per unieke content-pagina toe:
   1. een "Kort antwoord"-blok (40-60 woorden, extractie-klaar) direct onder de hero;
   2. dateModified (WebPage JSON-LD) voor freshness.
   Idempotent: draait 'Kort antwoord' / 'dateModified' niet dubbel.
   Draai:  node generator/aeo-enrich.js
   Raakt ALLEEN de pagina's in de answers-map hieronder aan. */

const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");
const TODAY = "2026-07-18";

const answers = {
  // ---- SITUATIES (vaststellingsovereenkomst/) ----
  "vaststellingsovereenkomst/reorganisatie.html": "Bij een reorganisatie is je vaststellingsovereenkomst een voorstel, geen verplichting. Je werkgever moet meestal het afspiegelingsbeginsel volgen, en bij een sociaal plan ligt de vergoeding vaak boven de wettelijke transitievergoeding. Teken niets onder druk, controleer de afspiegeling en of je WW veilig is, en onderhandel voordat je akkoord gaat.",
  "vaststellingsovereenkomst/boventallig-verklaard.html": "Boventallig betekent dat je arbeidsplaats vervalt, niet dat je slecht functioneert. Je werkgever moet eerst kijken naar een passende functie en de juiste selectieregels toepassen. Een daaropvolgende vaststellingsovereenkomst is onderhandelbaar: je hebt altijd bedenktijd en bijna altijd ruimte om over de vergoeding en je WW-zekerheid te onderhandelen.",
  "vaststellingsovereenkomst/tijdens-ziekte.html": "Teken een vaststellingsovereenkomst tijdens ziekte vrijwel nooit zomaar. Tijdens ziekte geldt een opzegverbod, en meewerken aan je ontslag kan zowel je Ziektewet- als je WW-rechten kosten. Alleen in specifieke situaties, zoals binnen een sociaal plan, kan tekenen verantwoord zijn. Laat je overeenkomst eerst beoordelen voordat je iets ondertekent.",
  "vaststellingsovereenkomst/zwangerschap.html": "Tijdens zwangerschap en bevallingsverlof geldt een bijzonder opzegverbod, en ontslag mag lang niet altijd. Meewerken aan je ontslag kan je bescherming en uitkeringsrechten aantasten. Is er sprake van onderscheid vanwege zwangerschap, dan sta je juridisch sterk. Teken niets zonder dat je situatie is beoordeeld op opzegverbod, discriminatie en je WW.",
  "vaststellingsovereenkomst/concurrentiebeding.html": "Als je werkgever afscheid van je neemt, is het vaak onredelijk je daarna aan een concurrentiebeding te houden. Bij een vaststellingsovereenkomst is dit bij uitstek onderhandelbaar: laat vastleggen dat het beding vervalt of wordt beperkt. Regel ook je relatiebeding en geheimhouding expliciet, anders zit je er na je vertrek alsnog aan vast.",
  "vaststellingsovereenkomst/oudere-werknemer.html": "Word je dicht bij je pensioen ontslagen, dan is de financiele inzet hoog: de weg naar nieuw werk is vaak langer en het inkomensgat tot je AOW groter. Let scherp op de hoogte van de vergoeding, een naadloze aansluiting op de WW en mogelijke overbrugging richting pensioen. Soms gelden er regelingen voor oudere werknemers.",
  "vaststellingsovereenkomst/disfunctioneren.html": "Voor ontslag wegens disfunctioneren gelden strenge eisen: een echt verbetertraject, dossieropbouw en een reele kans op verbetering. Ontbreekt dat, dan sta je sterk. Zorg dat in de vaststellingsovereenkomst een neutrale ontslaggrond staat, want komt disfunctioneren als verwijtbare reden erin, dan kan het UWV je WW weigeren.",
  "vaststellingsovereenkomst/verstoorde-arbeidsrelatie.html": "Een verstoorde arbeidsverhouding is een geldige, neutrale grond om uit elkaar te gaan met behoud van WW. Cruciaal is dat de schuldvraag niet bij jou wordt gelegd. Vaak is er ruimte om te onderhandelen over de vergoeding, vrijstelling van werk en een positief getuigschrift. Laat de formulering controleren voordat je tekent.",
  "vaststellingsovereenkomst/na-overname-of-fusie.html": "Bij een overgang van onderneming behoud je in principe je rechten en arbeidsvoorwaarden. Vervalt je functie door de reorganisatie die vaak op een fusie volgt, dan gelden de normale regels voor bedrijfseconomisch ontslag, inclusief afspiegeling en een eerlijke vergoeding. Let erop dat je verworven rechten en volledige diensttijd meetellen.",
  "vaststellingsovereenkomst/ontslag-door-ai.html": "Vervalt je functie door AI of automatisering, dan geldt juridisch hetzelfde als bij een klassieke reorganisatie: het is bedrijfseconomisch ontslag. Je werkgever moet de afspiegeling en selectieregels volgen, en je hebt recht op een eerlijke vergoeding en een veilige WW. Automatisering is geen reden om je minder te bieden.",
  "vaststellingsovereenkomst/tijdelijk-contract-niet-verlengd.html": "Bij een aflopend tijdelijk contract is een vaststellingsovereenkomst meestal niet nodig en soms zelfs nadelig. Vaak wil de werkgever er eerder mee afscheid nemen dan de einddatum. Beoordeel altijd of tekenen je iets oplevert of juist rechten kost, zoals je transitievergoeding, loon tot de einddatum of WW-opbouw.",
  "vaststellingsovereenkomst/vrijstelling-van-werk.html": "Vrijstelling van werk met behoud van salaris tot de einddatum is een waardevol onderhandelpunt: je kunt direct op zoek naar iets nieuws. Let op of de vrijstelling onherroepelijk is, zodat je niet kunt worden teruggeroepen, en op afspraken over je vakantiedagen en opgebouwd verlof. Regel dit expliciet in je overeenkomst.",
  "vaststellingsovereenkomst/finale-kwijting.html": "Met finale kwijting verklaren jij en je werkgever dat jullie na afwikkeling niets meer van elkaar te vorderen hebben. Daarom moet alles wat jou toekomt eerst goed geregeld zijn: je vergoeding, vakantiedagen, bonus, dertiende maand, onkosten en pensioen. Wat je vergeet te benoemen, ben je na je handtekening kwijt.",
  "vaststellingsovereenkomst/transitievergoeding-onderhandelen.html": "Bij een vaststellingsovereenkomst is de wettelijke transitievergoeding je bodem, niet je plafond. Je kunt vragen om meer: een hogere factor, langer doorbetaald met vrijstelling van werk, een budget voor scholing of outplacement, of het laten vervallen van een concurrentiebeding. Het eerste bod is bijna nooit het beste.",
  "vaststellingsovereenkomst/getuigschrift-en-referenties.html": "Hoe er over je vertrek wordt gesproken, bepaalt mede je volgende stap. Leg in de vaststellingsovereenkomst vast dat je een positief getuigschrift en een neutrale of positieve referentie krijgt, en spreek een gezamenlijke boodschap af richting collega's en buitenwereld. Zo houd je de regie over je reputatie.",
  "vaststellingsovereenkomst/vso-en-belasting.html": "Je ontslagvergoeding is belast als loon uit vroegere dienstbetrekking, dus je betaalt er belasting over in het jaar van uitkering. Een mooi brutobedrag is daardoor niet hetzelfde als wat je netto overhoudt. Soms kun je fiscaal gunstig spreiden of timen. Weet voor het tekenen wat je netto overhoudt, zodat je met echte cijfers onderhandelt.",
  "vaststellingsovereenkomst/na-lang-dienstverband.html": "Bij een lang dienstverband is je transitievergoeding hoger en weegt je ancienniteit zwaar, terwijl de weg naar nieuw werk soms langer is. Let scherp op de hoogte van de vergoeding, een eerlijke waardering van je jaren en een goede overgang naar WW of ander werk. Loyaliteit hoort beloond te worden, niet afgestraft.",
  "vaststellingsovereenkomst/onder-druk-getekend.html": "Een teken-vandaag-deadline of een tekenbonus voelt als dwang, maar het is onderhandelingsstrategie. Je hebt na ondertekening altijd een wettelijke bedenktermijn van 14 dagen, en 21 dagen als die termijn niet in de overeenkomst staat. Binnen die tijd mag je zonder opgaaf van reden terugkomen op je handtekening. Laat je dus niet opjagen.",
  "vaststellingsovereenkomst/werkgever-dreigt-met-uwv.html": "Je werkgever mag een ontslagprocedure bij het UWV of de rechter starten, maar dat kost tijd, geld en een sterk dossier. Juist daarom biedt men liever een vaststellingsovereenkomst aan. Een dreiging om je snel te laten tekenen zegt vaak iets over hun zwakke positie. Laat eerst beoordelen hoe kansrijk die procedure werkelijk zou zijn.",
  "vaststellingsovereenkomst/bedrijfsarts-adviseert-vso.html": "Een bedrijfsarts gaat over je herstel en re-integratie, niet over je ontslag. Een advies om tijdens ziekte een VSO te tekenen volg je nooit klakkeloos op: er geldt een opzegverbod, en meewerken aan je ontslag kan je Ziektewet- en WW-rechten kosten. Bereid je HR-gesprek voor, vraag alles schriftelijk en beslis niets ter plekke.",
  "vaststellingsovereenkomst/ziek-en-boventallig.html": "Tijdens ziekte geldt in beginsel een opzegverbod, ook bij een reorganisatie, dus je werkgever kan je niet zomaar via het UWV ontslaan. Een vaststellingsovereenkomst omzeilt dat verbod. Vaak is het verstandiger je herstel af te wachten. Teken alleen als je Ziektewet- en WW-rechten aantoonbaar goed geborgd zijn, bijvoorbeeld binnen een sociaal plan.",
  "vaststellingsovereenkomst/ww-aanvragen-na-vso.html": "Je WW gaat niet vanzelf in: vraag die zelf aan vanaf je eerste werkloze dag, uiterlijk binnen een week na je laatste werkdag. Het UWV kijkt naar je arbeidsverleden, gewerkte uren en laatstverdiende loon, dus houd je loonstroken en VSO bij de hand. Let op de fictieve opzegtermijn en blijf aantoonbaar solliciteren.",
  "vaststellingsovereenkomst/is-mijn-vso-een-goede-deal.html": "Een goede deal beoordeel je op het geheel, niet op het bedrag alleen. Kijk of je WW veilig is, of de einddatum en fictieve opzegtermijn kloppen, of je wordt vrijgesteld met behoud van salaris, of je bedingen vervallen en of je vakantiedagen, bonus en juridische kosten geregeld zijn. Een zwak punt kan een nette regeling alsnog slecht maken.",
  "vaststellingsovereenkomst/wat-is-gangbaar-onderhandelen.html": "Naast de transitievergoeding als bodem vragen mensen vaak om extra maanden salaris, een periode doorbetaald met vrijstelling van werk en vergoeding van hun juridische kosten (meestal 750 tot 1.000 euro). Ook gangbaar: het concurrentie- en relatiebeding laten vervallen, een positief getuigschrift en een budget voor scholing of outplacement.",
  "vaststellingsovereenkomst/vrijstelling-telt-als-vergoeding.html": "Doorbetaald worden tot je einddatum is gewoon loon voor de tijd dat je nog in dienst bent. Het is niet hetzelfde als een ontslagvergoeding, die compenseert voor het verlies van je baan. Een clausule die je vrijstelling wegstreept tegen je vergoeding, verkoopt je twee keer hetzelfde. Beoordeel beide onderdelen apart en laat de formulering controleren.",
  "vaststellingsovereenkomst/laten-controleren.html": "Wij controleren je vaststellingsovereenkomst gratis, vaak nog dezelfde dag. We kijken naar de ontslaggrond (blijft je WW veilig?), de hoogte van de vergoeding, de einddatum en fictieve opzegtermijn, de vrijstelling van werk, je bedingen, de eindafrekening en de finale kwijting. Wat je mist voordat je tekent, ben je daarna kwijt.",
  "vaststellingsovereenkomst/ontslag-met-wederzijds-goedvinden.html": "Ontslag met wederzijds goedvinden is in de praktijk hetzelfde als een vaststellingsovereenkomst. Wederzijds betekent niet dat je akkoord moet gaan: voor je WW wil het UWV zien dat het initiatief bij je werkgever lag en jou niets te verwijten valt. Je onderhandelt nog over de vergoeding en voorwaarden, en houdt na tekenen bedenktijd.",
  "vaststellingsovereenkomst/ww-uitkering-behouden.html": "Je behoudt na een vaststellingsovereenkomst in de regel je WW als de overeenkomst klopt. Het UWV wil zien dat het ontslag op initiatief van je werkgever is, op een neutrale of bedrijfseconomische grond zonder verwijt aan jou, en dat de einddatum de fictieve opzegtermijn respecteert. Een verkeerde formulering kan je maanden WW kosten.",
  "vaststellingsovereenkomst/opzegtermijn.html": "De einddatum in je VSO bepaalt wanneer je WW ingaat. Het UWV verwacht dat die datum de fictieve opzegtermijn respecteert: de opzegtermijn die bij een gewoon ontslag zou gelden. Ligt de einddatum te vroeg, dan gaat je WW later in terwijl je werkgever geen loon meer betaalt. Reken de juiste termijn uit op basis van je contract, cao en dienstjaren.",
  "vaststellingsovereenkomst/na-2-jaar-ziekte.html": "Na 104 weken ziekte stopt de loondoorbetaling en vervalt het opzegverbod, waarna vaak een VSO volgt. Is de re-integratie in spoor 1 en 2 niet goed doorlopen, dan kan het UWV een loonsanctie opleggen. Ben je nog geheel of deels arbeidsongeschikt, dan speelt je WIA-aanvraag mee. Laat eerst beoordelen of een WIA- of WW-traject beter past voordat je tekent.",
  "vaststellingsovereenkomst/kantonrechtersformule-of-transitievergoeding.html": "De oude kantonrechtersformule (factor A x B x C) is sinds 2015 geen norm meer. Nu is de transitievergoeding de wettelijke ondergrens: een derde maandsalaris per dienstjaar tot een maximum. Bij een vaststellingsovereenkomst is dat je startpunt, niet je plafond: je kunt een hogere factor onderhandelen, en bij ernstig verwijtbaar handelen komt er soms een billijke vergoeding bij.",
  "vaststellingsovereenkomst/concept-vaststellingsovereenkomst.html": "Een concept is een voorstel, geen eindversie: alles erin is nog bespreekbaar en je hoeft niets te tekenen totdat het klopt. Loop de kernafspraken punt voor punt na: ontslaggrond, einddatum, vergoeding, vrijstelling, bedingen en finale kwijting. Ontbreekt er iets of raakt een formulering je WW of vergoeding, dan stuur je een tegenvoorstel.",
  "vaststellingsovereenkomst/burn-out-en-vso.html": "Een burn-out telt als ziekte, dus geldt hetzelfde opzegverbod en moet je werkgever meewerken aan je herstel. Tekenen tijdens een burn-out kan je Ziektewet- en WW-rechten kosten. Is de burn-out ontstaan door een conflict of te hoge werkdruk, dan is mediation vaak een betere route. Teken pas als je voldoende hersteld bent of je uitkering veilig is.",
  "vaststellingsovereenkomst/collectief-ontslag.html": "Schrapt je werkgever twintig of meer banen binnen drie maanden, dan is er sprake van collectief ontslag en gelden er extra beschermingsregels. Je werkgever moet vooraf de vakbonden en het UWV raadplegen, en meestal volgt een sociaal plan met een betere vergoeding dan het minimum. Toets je persoonlijke aanbod aan dat plan voordat je tekent.",

  // ---- KENNISBANK-CLUSTERS (hulp/) ----
  "hulp/ontslag-op-staande-voet.html": "Ontslag op staande voet mag alleen bij een dringende reden, die onverwijld is gegeven en je meteen duidelijk is meegedeeld. Ontbreekt een van die eisen, dan houdt het meestal geen stand en sta je sterker dan je denkt. Teken niets, protesteer schriftelijk, blijf beschikbaar voor werk en schakel snel hulp in: de termijn om aan te vechten is kort.",
  "hulp/ziekte-en-reintegratie.html": "Als je ziek bent, sta je sterker dan je vaak voelt: er geldt een opzegverbod van maximaal twee jaar, je hebt recht op loondoorbetaling en je werkgever moet met je meewerken aan herstel volgens de Wet verbetering poortwachter. Over je belastbaarheid gaat de bedrijfsarts. Teken tijdens ziekte nooit zomaar een beeindiging.",
  "hulp/concurrentiebeding-en-andere-bedingen.html": "Een concurrentie-, relatie- of ronselbeding is niet automatisch geldig, ook al heb je getekend. In een tijdelijk contract is een beding alleen geldig met een schriftelijke motivering van zwaarwegend bedrijfsbelang. De rechter kan een beding beperken of vernietigen als het je onredelijk belemmert. Bij een vertrek is het bovendien onderhandelbaar: laat het checken voor je overstapt.",
  "hulp/arbeidsconflict.html": "Een verstoorde arbeidsrelatie is op zichzelf een geldige, neutrale grond om uit elkaar te gaan; het gevaar zit in de schuldvraag. Neem nooit in een opwelling zelf ontslag, want dat kost je meestal je WW. Vaak is mediation de beste eerste stap. Leg afspraken schriftelijk vast en win advies in voordat je iets ondertekent of toezegt.",
  "hulp/loonvordering.html": "Je loon hoort op de afgesproken datum betaald te worden. Gebeurt dat niet, dan heb je recht op je volledige loon, plus een wettelijke verhoging van maximaal 50 procent en wettelijke rente. Vaak is een stevige sommatiebrief al genoeg om het los te krijgen. Bewaar je loonstroken, contract en urenregistratie, en dring op tijd formeel aan.",
  "hulp/ongelijke-behandeling.html": "Gelijk of gelijkwaardig werk hoort gelijk beloond te worden; onderscheid op grond van bijvoorbeeld geslacht, leeftijd, afkomst of contractvorm mag niet zonder objectieve rechtvaardiging. Verzamel bewijs zoals functieomschrijvingen, salarisverschillen en beoordelingen, bespreek het intern, en leg het anders voor aan het College voor de Rechten van de Mens, dat laagdrempelig en kosteloos oordeelt.",

  // ---- KENNISBANK (handgemaakt, niet in data.js) ----
  "hulp/bedrijfseconomisch-ontslag.html": "Ontslag om bedrijfseconomische redenen (de a-grond) mag alleen als je werkgever aantoont dat je functie echt vervalt door bijvoorbeeld reorganisatie of bezuiniging. De route loopt via het UWV, en meestal geldt het afspiegelingsbeginsel om te bepalen wie boventallig wordt. Klopt de onderbouwing of de afspiegeling niet, dan sta je sterker dan je denkt.",
  "hulp/billijke-vergoeding.html": "De billijke vergoeding is een extra vergoeding bovenop de transitievergoeding, die je alleen krijgt als je werkgever zich ernstig verwijtbaar heeft gedragen. Er is geen vaste formule: de rechter bepaalt de hoogte op basis van de omstandigheden en het aangerichte nadeel. Bij een vaststellingsovereenkomst kun je zo'n vergoeding als onderhandelpunt inbrengen.",
  "hulp/dringende-reden.html": "Een dringende reden is een zo ernstige gedraging, zoals diefstal, fraude of bedreiging, dat van de werkgever niet gevraagd kan worden je in dienst te houden. Het ontslag moet bovendien onverwijld zijn gegeven en de reden meteen zijn meegedeeld. Ontbreekt de ernst of de snelheid, dan houdt het ontslag op staande voet vaak geen stand.",
  "hulp/eindafrekening.html": "In je eindafrekening staat alles wat je bij het einde van je dienstverband nog tegoed hebt: je laatste loon, vakantiegeld, niet-opgenomen vakantiedagen en een eventuele bonus of dertiende maand. Je hoort dit kort na je laatste werkdag uitbetaald te krijgen. Controleer de afrekening goed, want fouten of vergeten posten kosten je zomaar geld.",
  "hulp/emolumenten.html": "Emolumenten zijn arbeidsvoorwaarden bovenop je salaris, zoals een auto van de zaak, een bonus of een dertiende maand. Vaste, structurele emolumenten tellen vaak mee voor de hoogte van je transitievergoeding. Bij ontslag lever je bedrijfsmiddelen zoals de leaseauto meestal in; laat vastleggen wat meetelt voor je vergoeding en wanneer je precies inlevert.",
  "hulp/officiele-waarschuwing.html": "Een officiele waarschuwing is vaak de eerste stap in dossieropbouw richting ontslag. De wet noemt geen vast aantal waarschuwingen, maar voor ontslag wegens disfunctioneren is een zorgvuldig dossier met een verbetertraject nodig. Ben je het oneens met de waarschuwing, reageer dan schriftelijk en gemotiveerd, zodat ook jouw kant in het dossier komt.",
  "hulp/onterecht-ontslag.html": "Je ontslag is onterecht als er geen geldige grond is of de regels niet zijn gevolgd, bijvoorbeeld zonder dossier, zonder toestemming van UWV of rechter, of tijdens een opzegverbod. Je kunt het aanvechten of een vergoeding eisen, maar de termijnen zijn kort: meestal twee maanden. Kom dus snel in actie en teken niets wat je rechten wegneemt.",
  "hulp/ontslag-ouderschapsverlof.html": "Je mag niet worden ontslagen vanwege je ouderschapsverlof; dat is verboden onderscheid. Wel kan ontslag om een andere, losstaande reden, zoals een bedrijfseconomische reorganisatie, ook tijdens je verlof spelen. De reden van het ontslag bepaalt alles. Krijg je een vaststellingsovereenkomst tijdens je verlof, teken die dan niet zonder dat je situatie is beoordeeld.",
  "hulp/ontslaggronden.html": "De wet (artikel 7:669 BW) kent negen ontslaggronden, aangeduid met de letters a tot en met i, van bedrijfseconomisch ontslag en langdurige ziekte tot disfunctioneren en een verstoorde arbeidsverhouding. Bedrijfseconomisch ontslag en ontslag na twee jaar ziekte lopen via het UWV, de overige gronden via de kantonrechter. Bij een vaststellingsovereenkomst is geen ontslaggrond nodig.",
  "hulp/gevonden-worden-op-linkedin.html": "Een sterk LinkedIn-profiel zorgt dat nieuwe kansen jou vinden, en dat geeft je aan de onderhandeltafel het belangrijkste wat er is: een alternatief. Wie een alternatief heeft, tekent nooit uit angst. Richt je profiel in als etalage, niet als cv: kies de juiste zoekwoorden, gebruik open-for-work slim en blijf zichtbaar, zodat recruiters je vanzelf benaderen.",

  // ---- TOOLS (interactief: kort wat de tool doet en oplevert) ----
  "tools/transitievergoeding-berekenen.html": "Met deze rekentool zie je direct een indicatie van je wettelijke transitievergoeding: vul je bruto maandsalaris (inclusief vakantiegeld), je datum in dienst en je laatste werkdag in. De formule is een derde maandsalaris per dienstjaar, met in 2026 een maximum van 102.000 euro of een jaarsalaris. Bij een vaststellingsovereenkomst is dit je startpunt, niet je plafond.",
  "tools/ww-veilig-scan.html": "Met deze scan zie je in vijf korte vragen of je vaststellingsovereenkomst je WW-uitkering veilig stelt. Je WW blijft in de regel behouden als het ontslag op initiatief van je werkgever is, de grond neutraal is en de einddatum de fictieve opzegtermijn respecteert. Twijfel je bij een vraag, laat de tekst dan gratis checken voordat je tekent.",
  "tools/bedenktermijn-berekenen.html": "Met deze tool zie je precies hoeveel bedenktijd je nog hebt na het tekenen van je vaststellingsovereenkomst. Je hebt wettelijk 14 dagen om zonder opgaaf van reden op je handtekening terug te komen, en 21 dagen als die termijn niet in de overeenkomst staat. Vul je tekendatum in en je ziet je resterende dagen.",
  "tools/wat-is-mijn-vso-waard.html": "Met deze tool vergelijk je je aangeboden vergoeding met de wettelijke transitievergoeding, zodat je ziet of je aanbod aan de veilige kant zit of dat er waarschijnlijk meer in zit. Vul drie gegevens in voor een directe indicatie. Onthoud dat de transitievergoeding de bodem is: bij een vaststellingsovereenkomst valt vaak meer te onderhandelen.",
  "tools/mag-mijn-werkgever-druk-zetten.html": "Met deze check zie je meteen of de druk die je voelt terecht is. Een teken-vandaag-deadline, een tekenbonus of dreigen met het UWV zijn onderhandelingstactiek, geen verplichting. Je houdt altijd je wettelijke bedenktermijn van 14 dagen, en 21 dagen als die niet vermeld staat. Vink aan wat er speelt en zie waar je recht op houdt."
};

const box = ans => `<section class="block"><div class="wrap"><div class="prose reveal" style="border-left:4px solid var(--gold-deep);background:rgba(190,150,70,.06);border-radius:12px;padding:18px 22px"><p style="margin:0"><strong>Kort antwoord:</strong> ${ans}</p></div></div></section>\n`;

let nAns = 0, nDate = 0, nMiss = 0, nNoAnchor = 0;
for (const [rel, text] of Object.entries(answers)) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) { console.log("ONTBREEKT:", rel); nMiss++; continue; }
  let html = fs.readFileSync(p, "utf8");
  let changed = false;

  if (!html.includes("Kort antwoord")) {
    const idx = html.indexOf('<section class="block">');
    if (idx !== -1) {
      html = html.slice(0, idx) + box(text) + html.slice(idx);
      nAns++; changed = true;
    } else { console.log("GEEN ANKER:", rel); nNoAnchor++; }
  }

  if (!html.includes("dateModified")) {
    const m = html.match(/<link rel="canonical" href="([^"]+)"/);
    const url = m ? m[1] : "";
    const ld = `<script type="application/ld+json">{"@context":"https://schema.org","@type":"WebPage","url":"${url}","dateModified":"${TODAY}"}</script>\n`;
    html = html.replace("</head>", ld + "</head>");
    nDate++; changed = true;
  }

  if (changed) fs.writeFileSync(p, html, "utf8");
}
console.log(`Klaar. direct-antwoord toegevoegd: ${nAns}, dateModified toegevoegd: ${nDate}, ontbrekend: ${nMiss}, geen anker: ${nNoAnchor}`);