// Databron voor de SEO-paginagenerator van Eerste hulp bij VSO.
// Elk item bevat UNIEKE, inhoudelijke velden zodat gegenereerde pagina's
// geen dunne doorway-pages worden. Uitbreiden = simpelweg een record toevoegen.

const WA = "31645733083";

// ---------------------------------------------------------------------------
// BEDRIJVEN — reorganisatie-/bedrijfspagina's.
// verified:true = publiek bekend cijfer (juli 2026). Anders sector-framing zonder verzonnen getallen.
// ---------------------------------------------------------------------------
const companies = [
  { slug:"heineken", name:"Heineken", sector:"food & beverage", hq:"amsterdam", verified:true,
    reorg:"Heineken heeft aangekondigd de komende jaren wereldwijd fors te reorganiseren, waarbij naar verluidt duizenden functies verdwijnen. Dat raakt ook Nederlandse vestigingen en kantoorfuncties.",
    tone:"Je gaf misschien jaren aan dit merk, en toch lig je nu op de lijst." },
  { slug:"asml", name:"ASML", sector:"halfgeleiders & hightech", hq:"veldhoven", verified:true,
    reorg:"ASML kondigde eerder in 2026 aan circa 1.700 banen te schrappen. Voor een regio die grotendeels om ASML draait, betekent dat veel gezinnen tegelijk in onzekerheid.",
    tone:"In de Brainport-regio voelt een ontslag bij ASML als de grond onder je voeten." },
  { slug:"abn-amro", name:"ABN AMRO", sector:"bank & financiële dienstverlening", hq:"amsterdam", verified:true,
    reorg:"ABN AMRO heeft aangekondigd tot wel 5.200 arbeidsplaatsen te schrappen richting 2028, bijna een vijfde van het personeelsbestand. Digitalisering en AI spelen daarin een hoofdrol.",
    tone:"Na jaren trouwe dienst bij de bank hoor je ineens dat je functie verdwijnt." },
  { slug:"ing", name:"ING", sector:"bank & financiële dienstverlening", hq:"amsterdam", verified:true,
    reorg:"ING heeft gemeld dat digitalisering en kunstmatige intelligentie richting eind 2026 zo'n 950 functies overbodig kunnen maken. Vooral ondersteunende en IT-rollen zijn in beeld.",
    tone:"Je hield de bank draaiende, en nu blijkt een algoritme je werk over te nemen." },
  { slug:"de-volksbank", name:"de Volksbank (ASN, SNS, RegioBank)", sector:"bank & financiële dienstverlening", hq:"utrecht", verified:true,
    reorg:"Binnen de Volksbank, waaronder ASN Bank, gaan naar verwachting 850 tot 950 banen verloren, ongeveer een kwart van alle posities. Een ingrijpende reorganisatie voor een relatief klein huis.",
    tone:"Bij een bank met een hart voor duurzaamheid verwacht je zo'n klap niet." },
  { slug:"oracle", name:"Oracle Nederland", sector:"IT & software", hq:"utrecht", verified:true,
    reorg:"Oracle voerde in 2026 een omvangrijke ontslagronde door, die samenviel met bredere verschuivingen in de techsector richting AI en cloud.",
    tone:"In tech gaat het snel: het ene kwartaal held, het volgende boventallig." },
  { slug:"philips", name:"Philips", sector:"health technology", hq:"amsterdam", verified:false,
    reorg:"Philips reorganiseert de afgelopen jaren stevig en blijft zijn organisatie afslanken. In de health-technologiesector volgen efficiencyslagen elkaar snel op.",
    tone:"Een icoon van Nederlandse techniek, en toch sta jij nu op de tocht." },
  { slug:"kpn", name:"KPN", sector:"telecom", hq:"rotterdam", verified:false,
    reorg:"Telecombedrijven als KPN automatiseren en digitaliseren in hoog tempo, met periodieke reorganisaties van ondersteunende en technische functies tot gevolg.",
    tone:"Je verbond heel Nederland, en nu voel je je zelf even afgesloten." },
  { slug:"rabobank", name:"Rabobank", sector:"bank & financiële dienstverlening", hq:"utrecht", verified:false,
    reorg:"De hele bankensector staat in 2026 onder druk van AI en kostenbesparing. Ook coöperatieve banken passen hun personeelsbestand daarop aan.",
    tone:"Ook bij een coöperatie draait het uiteindelijk om cijfers, merk je nu." },
  { slug:"shell", name:"Shell", sector:"energie", hq:"den-haag", verified:false,
    reorg:"Grote energiebedrijven herstructureren rond de energietransitie en kostenbeheersing, met gevolgen voor kantoor- en staffuncties.",
    tone:"Een wereldspeler op je cv, en toch sta je ineens buiten." },
  { slug:"booking-com", name:"Booking.com", sector:"tech & reizen", hq:"amsterdam", verified:false,
    reorg:"Techplatforms schalen hun personeel op en af met de markt. Ook bij grote Amsterdamse techwerkgevers zijn reorganisaties geen uitzondering.",
    tone:"In de dynamiek van tech kan een groeibedrijf ineens moeten snijden." },
  { slug:"capgemini", name:"Capgemini", sector:"IT-consultancy", hq:"utrecht", verified:false,
    reorg:"In de IT-consultancy geldt vaak een 'up or out'-cultuur. Als projecten teruglopen of AI taken overneemt, volgt al snel een beëindigingsvoorstel.",
    tone:"Je factureerde topuren, en toch pas je ineens niet meer in de piramide." },
  { slug:"accenture", name:"Accenture", sector:"IT-consultancy", hq:"amsterdam", verified:false,
    reorg:"Grote consultancyhuizen sturen scherp op bezetting en marges. Bij tegenwind wordt er via vaststellingsovereenkomsten afscheid genomen.",
    tone:"In consultancy ben je zo waardevol als je laatste project." },
  { slug:"postnl", name:"PostNL", sector:"post & logistiek", hq:"den-haag", verified:false,
    reorg:"Dalende postvolumes en automatisering zetten de organisatie van postbedrijven blijvend onder druk, met reorganisaties tot gevolg.",
    tone:"Je bezorgde het nieuws van heel Nederland, nu is het jouw beurt om slecht nieuws te krijgen." },
  { slug:"nxp", name:"NXP Semiconductors", sector:"halfgeleiders & hightech", hq:"eindhoven", verified:false,
    reorg:"De chipsector is cyclisch. Na sterke jaren volgen correcties, waarbij ook in de Brainport-regio functies kunnen vervallen.",
    tone:"De chip-industrie draait op golven, en deze keer sta jij in het dal." },
  { slug:"tomtom", name:"TomTom", sector:"IT & software", hq:"amsterdam", verified:false,
    reorg:"Techbedrijven verschuiven zwaartepunten naar AI en automatisering. Dat leidt met regelmaat tot herstructurering van teams.",
    tone:"Je hielp de wereld de weg te vinden, en verloor even je eigen richting." },
  { slug:"unilever", name:"Unilever", sector:"consumentengoederen & food", hq:"rotterdam", verified:false,
    reorg:"Grote consumentengoederenconcerns stroomlijnen hun merkenportefeuille en organisatie voortdurend, met reorganisaties van kantoor- en staffuncties tot gevolg.",
    tone:"Je bouwde mee aan merken die iedereen kent, en toch sta jij nu buiten beeld." },
  { slug:"ahold-delhaize", name:"Ahold Delhaize", sector:"retail & supermarkten", hq:"zaandam", verified:false,
    reorg:"In retail draait alles om marges en efficiency. Digitalisering van winkels en distributie leidt regelmatig tot het schrappen van functies op het hoofdkantoor.",
    tone:"Je hield de schappen van Nederland gevuld, en nu voel je je zelf even leeg." },
  { slug:"albert-heijn", name:"Albert Heijn", sector:"retail & supermarkten", hq:"zaandam", verified:false,
    reorg:"Supermarktketens automatiseren logistiek en kantoorprocessen in hoog tempo, wat periodiek tot reorganisaties van ondersteunende functies leidt.",
    tone:"Je zorgde dat het boodschappenmandje van Nederland klopte, en nu klopt jouw wereld even niet meer." },
  { slug:"bol", name:"bol", sector:"e-commerce & tech", hq:"utrecht", verified:false,
    reorg:"E-commerceplatforms schalen hun teams op en af met de markt en automatiseren steeds meer. Reorganisaties horen daar helaas bij.",
    tone:"In de wereld van online winkelen gaat het snel, ook als het je eigen baan betreft." },
  { slug:"adyen", name:"Adyen", sector:"fintech & betalen", hq:"amsterdam", verified:false,
    reorg:"Fintechbedrijven sturen scherp op efficiency en tempo. Na sterke groeijaren volgen soms correcties in de bezetting.",
    tone:"Je hielp betalingen wereldwijd soepel te laten lopen, en nu hapert je eigen zekerheid." },
  { slug:"randstad", name:"Randstad", sector:"HR & arbeidsbemiddeling", hq:"amsterdam", verified:false,
    reorg:"Zelfs in de HR-sector zorgt digitalisering voor herstructurering. Juist een uitzendreus past zijn eigen organisatie regelmatig aan de markt aan.",
    tone:"Je hielp anderen aan werk, en zoekt nu ineens zelf de weg vooruit." },
  { slug:"aegon", name:"Aegon", sector:"verzekeringen & pensioenen", hq:"den-haag", verified:false,
    reorg:"Verzekeraars digitaliseren en automatiseren stevig, met AI die administratieve functies overneemt. Reorganisaties zijn daardoor geen uitzondering.",
    tone:"Je regelde de zekerheid van anderen, en verliest nu even die van jezelf." },
  { slug:"nationale-nederlanden", name:"Nationale-Nederlanden", sector:"verzekeringen & pensioenen", hq:"den-haag", verified:false,
    reorg:"In de verzekeringssector versnelt de automatisering. Dat betekent periodiek afscheid van ondersteunende en administratieve rollen.",
    tone:"Je stond voor vertrouwen en continuïteit, en nu is jouw continuïteit in het geding." },
  { slug:"achmea", name:"Achmea", sector:"verzekeringen", hq:"apeldoorn", verified:false,
    reorg:"Grote verzekeraars stroomlijnen hun processen rond AI en digitale dienstverlening, met reorganisaties van kantoorfuncties tot gevolg.",
    tone:"Je hielp mensen bij tegenslag, en nu overkomt de tegenslag jou." },
  { slug:"asr", name:"a.s.r.", sector:"verzekeringen & pensioenen", hq:"utrecht", verified:false,
    reorg:"Na fusies en digitalisering herschikken verzekeraars hun organisatie. Dubbele functies en handmatige processen verdwijnen daarbij vaak.",
    tone:"Je zorgde voor de toekomst van anderen, en nu is die van jou onzeker." },
  { slug:"dsm-firmenich", name:"dsm-firmenich", sector:"chemie & life sciences", hq:"maastricht", verified:false,
    reorg:"Na een grote fusie volgt vaak een integratie waarbij overlappende functies vervallen. In chemie en life sciences telt elke efficiencyslag.",
    tone:"Je werkte aan de wetenschap achter het dagelijks leven, en nu staat je eigen leven op de kop." },
  { slug:"akzonobel", name:"AkzoNobel", sector:"chemie & coatings", hq:"amsterdam", verified:false,
    reorg:"Industriële concerns snijden in kosten om concurrerend te blijven. Dat raakt met regelmaat kantoor- en productiefuncties.",
    tone:"Je gaf letterlijk kleur aan de wereld, en nu voelt alles even grijs." },
  { slug:"frieslandcampina", name:"FrieslandCampina", sector:"food & zuivel", hq:"amersfoort", verified:false,
    reorg:"Zuivelconcerns reorganiseren rond efficiency en veranderende markten, waarbij ook hoofdkantoorfuncties op de tocht kunnen komen.",
    tone:"Je werkte voor een coöperatie van boeren, en toch voel je je nu alleen staan." },
  { slug:"vodafoneziggo", name:"VodafoneZiggo", sector:"telecom", hq:"utrecht", verified:false,
    reorg:"Telecombedrijven automatiseren klantcontact en netwerkbeheer, wat periodiek tot het schrappen van functies leidt.",
    tone:"Je hield Nederland verbonden, en nu voel je je zelf even buitengesloten." },
  { slug:"odido", name:"Odido", sector:"telecom", hq:"den-haag", verified:false,
    reorg:"Na een rebranding en integratie stroomlijnen telecomaanbieders hun organisatie, met reorganisaties tot gevolg.",
    tone:"Je bouwde aan een nieuw merk, en nu bouw je onverwacht aan een nieuwe toekomst." },
  { slug:"ns", name:"NS", sector:"openbaar vervoer", hq:"utrecht", verified:false,
    reorg:"Ook bij vervoersbedrijven zorgen digitalisering en kostendruk voor herstructurering van staf- en kantoorfuncties.",
    tone:"Je bracht heel Nederland op tijd op zijn bestemming, en nu is je eigen bestemming onzeker." },
  { slug:"schiphol", name:"Schiphol", sector:"luchtvaart & logistiek", hq:"hoofddorp", verified:false,
    reorg:"De luchtvaartsector kent grote schommelingen. Efficiencyslagen en automatisering raken met regelmaat de organisatie rond de luchthaven.",
    tone:"Je hield de poort van Nederland naar de wereld open, en nu staat jouw deur op een kier." },
  { slug:"klm", name:"KLM", sector:"luchtvaart", hq:"amstelveen", verified:false,
    reorg:"Luchtvaartmaatschappijen sturen scherp op kosten en productiviteit. Bij tegenwind volgen reorganisaties van grond- en kantoorfuncties.",
    tone:"Je hielp mensen de wereld over, en nu zoek je zelf een nieuwe richting." },
  { slug:"tata-steel", name:"Tata Steel", sector:"staal & industrie", hq:"haarlem", verified:false,
    reorg:"De staalindustrie staat onder druk van kosten, verduurzaming en marktomstandigheden, met reorganisaties tot gevolg.",
    tone:"Je werkte in het hart van de Nederlandse industrie, en nu voelt de grond onvast." },
  { slug:"signify", name:"Signify", sector:"verlichting & technologie", hq:"eindhoven", verified:false,
    reorg:"Techbedrijven in de Brainport-regio passen hun organisatie aan veranderende markten en automatisering aan.",
    tone:"Je bracht licht in huizen wereldwijd, en nu is het even donker voor jezelf." },
  { slug:"vanderlande", name:"Vanderlande", sector:"logistieke techniek", hq:"veldhoven", verified:false,
    reorg:"Bedrijven in logistieke automatisering bewegen mee met de investeringscycli van hun klanten, wat de bezetting kan beïnvloeden.",
    tone:"Je automatiseerde de magazijnen van de wereld, en nu verandert je eigen situatie." },
  { slug:"deloitte", name:"Deloitte", sector:"consultancy & accountancy", hq:"rotterdam", verified:false,
    reorg:"Grote advies- en accountantskantoren sturen scherp op bezetting en marges. Bij tegenwind wordt via vaststellingsovereenkomsten afscheid genomen.",
    tone:"Je adviseerde de top van het bedrijfsleven, en nu heb je zelf even advies nodig." },
  { slug:"ibm-nederland", name:"IBM Nederland", sector:"IT & consultancy", hq:"amsterdam", verified:false,
    reorg:"Grote IT-dienstverleners verschuiven hun zwaartepunt naar AI en cloud, waarbij traditionele functies onder druk staan.",
    tone:"Je bouwde aan de systemen van morgen, en toch past je eigen rol er ineens niet meer bij." },
  { slug:"microsoft-nederland", name:"Microsoft Nederland", sector:"IT & cloud", hq:"amsterdam", verified:false,
    reorg:"Ook de grootste techbedrijven herschikken hun teams rond AI en cloud, met periodieke reorganisaties tot gevolg.",
    tone:"Je werkte bij een gigant, en toch voel je je vandaag heel klein." },
  { slug:"coolblue", name:"Coolblue", sector:"e-commerce & retail", hq:"rotterdam", verified:false,
    reorg:"E-commercebedrijven schalen hun teams op en af met de markt en automatiseren steeds meer processen. Reorganisaties van kantoor- en ondersteunende functies horen daarbij.",
    tone:"Je zorgde elke dag voor de glimlach van klanten, en nu is het even jouw dag niet." },
  { slug:"picnic", name:"Picnic", sector:"online supermarkt & logistiek", hq:"amsterdam", verified:false,
    reorg:"Snelgroeiende bezorgbedrijven passen hun organisatie voortdurend aan de markt aan, wat periodiek tot herstructurering leidt.",
    tone:"Je hielp Nederland zijn boodschappen bezorgen, en nu sta je zelf voor een dichte deur." },
  { slug:"jumbo", name:"Jumbo", sector:"retail & supermarkten", hq:"den-bosch", verified:false,
    reorg:"Supermarktketens automatiseren logistiek en kantoorprocessen, wat periodiek tot reorganisaties van ondersteunende functies leidt.",
    tone:"Je hield de winkels van Nederland draaiende, en nu draait alles even om jou." },
  { slug:"apg", name:"APG", sector:"pensioenuitvoerder", hq:"heerlen", verified:false,
    reorg:"Pensioenuitvoerders staan door de nieuwe pensioenwet en digitalisering onder grote druk, met ingrijpende reorganisaties tot gevolg.",
    tone:"Je regelde de oude dag van miljoenen mensen, en nu is je eigen toekomst onzeker." },
  { slug:"alliander", name:"Alliander", sector:"netbeheer & energie", hq:"arnhem", verified:false,
    reorg:"Netbeheerders reorganiseren rond de energietransitie en digitalisering, waarbij staf- en kantoorfuncties kunnen vervallen.",
    tone:"Je hield het licht aan bij iedereen, en nu tast je zelf even in het donker." },
  { slug:"eneco", name:"Eneco", sector:"energie", hq:"rotterdam", verified:false,
    reorg:"Energiebedrijven herstructureren rond de energietransitie en kostenbeheersing, met gevolgen voor kantoorfuncties.",
    tone:"Je werkte aan de energie van morgen, en nu is je eigen morgen onzeker." },
  { slug:"vattenfall", name:"Vattenfall", sector:"energie", hq:"amsterdam", verified:false,
    reorg:"Grote energieconcerns stroomlijnen hun organisatie rond verduurzaming en efficiency, met reorganisaties tot gevolg.",
    tone:"Je bracht warmte in huizen, en nu voel je zelf de kou van onzekerheid." },
  { slug:"arcadis", name:"Arcadis", sector:"engineering & advies", hq:"amsterdam", verified:false,
    reorg:"Advies- en ingenieursbureaus sturen scherp op bezetting en projectportefeuille. Bij tegenwind wordt via vaststellingsovereenkomsten afscheid genomen.",
    tone:"Je bouwde mee aan de wereld van morgen, en toch pas je er ineens niet meer in." },
  { slug:"exact", name:"Exact", sector:"software", hq:"delft", verified:false,
    reorg:"Softwarebedrijven verschuiven hun zwaartepunt naar cloud en AI, waarbij traditionele functies onder druk staan.",
    tone:"Je bouwde aan de systemen van ondernemers, en nu hapert je eigen zekerheid." },
  { slug:"basic-fit", name:"Basic-Fit", sector:"fitness & retail", hq:"hoofddorp", verified:false,
    reorg:"Ketens met veel vestigingen stroomlijnen hun hoofdkantoor en ondersteuning, met periodieke reorganisaties tot gevolg.",
    tone:"Je hield anderen fit en in beweging, en nu sta jij zelf even stil." },
  { slug:"thales-nederland", name:"Thales Nederland", sector:"defensie & technologie", hq:"hengelo", verified:false,
    reorg:"Hightech- en defensiebedrijven bewegen mee met opdrachtcycli, wat de bezetting van bepaalde functies kan beïnvloeden.",
    tone:"Je werkte aan geavanceerde techniek, en toch verandert je eigen situatie plots." },
  { slug:"vdl-groep", name:"VDL Groep", sector:"industrie & techniek", hq:"eindhoven", verified:false,
    reorg:"Industriële maakbedrijven zijn conjunctuurgevoelig. Na sterke jaren volgen correcties, waarbij ook in de Brainport-regio functies kunnen vervallen.",
    tone:"Je stond in het hart van de Brabantse maakindustrie, en nu voelt de grond onvast." },
  { slug:"projective-group", name:"Projective Group", sector:"consultancy & financiële dienstverlening", hq:"amsterdam", verified:false,
    reorg:"Consultancybureaus in de financiële sector schalen mee met klantopdrachten. Als projecten aflopen of de markt afkoelt, wordt er kritisch naar de bezetting gekeken.",
    tone:"Je adviseerde anderen bij verandering, en nu sta je zelf voor die keuze." },
  { slug:"pwc", name:"PwC", sector:"accountancy & advies", hq:"amsterdam", verified:false,
    reorg:"Grote accountants- en advieskantoren herstructureren geregeld hun adviestakken en ondersteunende diensten als de markt of regelgeving verandert.",
    tone:"Je hielp anderen hun cijfers en risico's op orde te krijgen, en nu draait het even om die van jou." },
  { slug:"ey", name:"EY", sector:"accountancy & advies", hq:"amsterdam", verified:false,
    reorg:"Bij de grote vier wisselen opdrachtvolumes snel. Als een adviespraktijk krimpt, wordt er kritisch naar de bezetting gekeken.",
    tone:"Je adviseerde over transacties en transities, en nu maak je er zelf een door." },
  { slug:"kpmg", name:"KPMG", sector:"accountancy & advies", hq:"amstelveen", verified:false,
    reorg:"Audit- en advieskantoren stroomlijnen hun teams zodra de klantvraag of de strategische focus verschuift.",
    tone:"Je stond bekend om je scherpe analyses, laat die nu ook voor jezelf werken." },
  { slug:"mckinsey", name:"McKinsey & Company", sector:"strategieconsultancy", hq:"amsterdam", verified:false,
    reorg:"Strategieconsultants schalen mee met de economie. In rustiger jaren wordt de instroom geremd en de bezetting herzien.",
    tone:"Je adviseerde de top over moeilijke keuzes, en nu sta je zelf voor er een." },
  { slug:"sopra-steria", name:"Sopra Steria", sector:"IT-dienstverlening", hq:"nieuwegein", verified:false,
    reorg:"IT-dienstverleners draaien op meerjarige contracten. Als een groot contract afloopt, verandert de personeelsbehoefte snel.",
    tone:"Je bouwde aan de systemen van anderen, en nu verandert je eigen structuur." },
  { slug:"atos-nederland", name:"Atos Nederland", sector:"IT-dienstverlening", hq:"amstelveen", verified:false,
    reorg:"Internationale IT-concerns reorganiseren geregeld hun landenorganisaties om kosten en focus bij te sturen.",
    tone:"Je hield complexe IT-omgevingen draaiend, en toch hapert je eigen situatie nu." },
  { slug:"salesforce-nederland", name:"Salesforce Nederland", sector:"software & cloud", hq:"amsterdam", verified:false,
    reorg:"Amerikaanse softwarebedrijven passen hun wereldwijde teams aan bij tegenvallende groei, wat ook de Nederlandse vestiging raakt.",
    tone:"Je verkocht groei en verandering, en nu overkomt de verandering jou." },
  { slug:"sap-nederland", name:"SAP Nederland", sector:"software & cloud", hq:"den-bosch", verified:false,
    reorg:"Grote softwareleveranciers verschuiven naar cloud en AI, waarbij bepaalde functies verdwijnen en andere ontstaan.",
    tone:"Je hielp bedrijven transformeren, tijd om je eigen volgende stap slim te zetten." },
  { slug:"just-eat-takeaway", name:"Just Eat Takeaway", sector:"e-commerce & platform", hq:"amsterdam", verified:false,
    reorg:"Bezorgplatforms hebben na jaren van snelle groei hun organisatie ingedikt en teams samengevoegd.",
    tone:"Je zorgde dat alles op tijd bezorgd werd, laat je eigen deal nu niet overhaasten." },
  { slug:"hema", name:"HEMA", sector:"retail & warenhuis", hq:"amsterdam", verified:false,
    reorg:"Warenhuisketens moderniseren hun formule en hoofdkantoor, met periodieke reorganisaties tot gevolg.",
    tone:"Je hoorde bij een merk dat iedereen kent, en nu voelt het opeens onzeker." },
  { slug:"action", name:"Action", sector:"retail & logistiek", hq:"hoorn", verified:false,
    reorg:"Snelgroeiende discounters centraliseren en automatiseren hun distributie, waardoor functies verschuiven of vervallen.",
    tone:"Je hield de schappen en de logistiek op orde, nu is het jouw beurt om goed geregeld te worden." },
  { slug:"mediamarkt-nederland", name:"MediaMarkt Nederland", sector:"retail & elektronica", hq:"rotterdam", verified:false,
    reorg:"Elektronicaketens verschuiven naar online en verkleinen hun winkel- en kantoororganisatie.",
    tone:"Je adviseerde klanten over hun keuzes, maak nu een goede keuze voor jezelf." },
  { slug:"ikea-nederland", name:"IKEA Nederland", sector:"retail & wonen", hq:"amsterdam", verified:false,
    reorg:"Grote woonwarenhuizen herzien hun service- en kantoororganisatie naarmate ze verder digitaliseren.",
    tone:"Je hielp mensen aan een nieuw thuis, zorg dat je eigen basis stevig blijft." },
  { slug:"sabic", name:"Sabic", sector:"chemie & industrie", hq:"sittard-geleen", verified:false,
    reorg:"De chemie op Chemelot is conjunctuur- en energieprijsgevoelig. Bij tegenwind worden productie en staf herzien.",
    tone:"Je werkte in het hart van de Limburgse chemie, en nu verandert de grond onder je voeten." },
  { slug:"boskalis", name:"Boskalis", sector:"maritiem & baggeren", hq:"dordrecht", verified:false,
    reorg:"Baggeraars en offshorebedrijven bewegen mee met wereldwijde projectcycli, wat de bezetting laat schommelen.",
    tone:"Je verlegde letterlijk kustlijnen, en nu verlegt je eigen loopbaan zich." },
  { slug:"tennet", name:"TenneT", sector:"energie & netbeheer", hq:"arnhem", verified:false,
    reorg:"Netbeheerders herverdelen werk en reorganiseren terwijl ze fors investeren in de energietransitie.",
    tone:"Je hield het licht aan voor het land, laat nu iemand naast jou staan." },
  { slug:"gasunie", name:"Gasunie", sector:"energie & infrastructuur", hq:"groningen", verified:false,
    reorg:"De energie-infrastructuur verschuift van gas naar waterstof en warmte, waardoor functies veranderen of vervallen.",
    tone:"Je werkte aan de energie van morgen, en toch is je eigen situatie vandaag onzeker." },
  { slug:"jde", name:"JDE (Jacobs Douwe Egberts)", sector:"food & FMCG", hq:"amsterdam", verified:false,
    reorg:"Internationale voedingsconcerns stroomlijnen merken en hoofdkantoorfuncties na fusies en overnames.",
    tone:"Je zorgde voor het kopje koffie van miljoenen, tijd om even bij jezelf stil te staan." },
  { slug:"janssen", name:"Janssen (Johnson & Johnson)", sector:"farma & life sciences", hq:"leiden", verified:false,
    reorg:"Farmaceuten schalen onderzoeks- en productieteams op en af rond de levenscyclus van medicijnen.",
    tone:"Je werkte aan de gezondheid van anderen, zorg nu goed voor je eigen toekomst." },
  { slug:"msd-nederland", name:"MSD Nederland", sector:"farma & life sciences", hq:"oss", verified:false,
    reorg:"Life-sciencesbedrijven in Oss herzien geregeld hun onderzoeks- en productieafdelingen bij een verschuivende pijplijn.",
    tone:"Je stond aan de basis van nieuwe medicijnen, en nu heb je zelf een goede remedie nodig." },
  { slug:"triodos-bank", name:"Triodos Bank", sector:"bank & duurzame financiering", hq:"utrecht", verified:false,
    reorg:"Ook duurzame banken verlagen hun kosten en digitaliseren, waardoor traditionele functies verdwijnen.",
    tone:"Je koos bewust voor werk met betekenis, laat je afscheid dan net zo zorgvuldig zijn." },
  { slug:"van-lanschot-kempen", name:"Van Lanschot Kempen", sector:"private bank & vermogensbeheer", hq:"den-bosch", verified:false,
    reorg:"Private banks stroomlijnen hun organisatie en automatiseren processen naarmate vermogensbeheer verder digitaliseert.",
    tone:"Je beheerde het vermogen van anderen, tijd om je eigen belang scherp te bewaken." },
  { slug:"nibc", name:"NIBC", sector:"bank & financiering", hq:"den-haag", verified:false,
    reorg:"Kleinere banken passen hun organisatie aan bij overnames, strategiewijzigingen en toenemende automatisering.",
    tone:"Je werkte in een wereld van deals, zorg nu dat je eigen deal klopt." },
  { slug:"bunq", name:"bunq", sector:"neobank & fintech", hq:"amsterdam", verified:false,
    reorg:"Snelgroeiende fintechs schalen hun teams net zo hard bij als ze groeiden zodra de focus verschuift.",
    tone:"Je hoorde bij de digitale voorhoede, en toch is je eigen toekomst nu even onzeker." },
  { slug:"zilveren-kruis", name:"Zilveren Kruis", sector:"zorgverzekeraar", hq:"leiden", verified:false,
    reorg:"Zorgverzekeraars centraliseren productontwikkeling, communicatie en marketing, waar reorganisaties functies raken.",
    tone:"Je hielp anderen aan goede zorg, zorg nu ook goed voor jezelf." },
  { slug:"centraal-beheer", name:"Centraal Beheer", sector:"verzekeraar", hq:"apeldoorn", verified:false,
    reorg:"Verzekeraars digitaliseren hun dienstverlening, waardoor traditionele kantoorfuncties verdwijnen of veranderen.",
    tone:"Je hoorde bij een vertrouwd Apeldoorns merk, en nu verandert je eigen situatie." },
  { slug:"menzis", name:"Menzis", sector:"zorgverzekeraar", hq:"groningen", verified:false,
    reorg:"Zorgverzekeraars staan onder kostendruk en herzien hun organisatie en ondersteunende afdelingen.",
    tone:"Je zette je in voor de gezondheid van anderen, nu telt jouw welzijn even." },
  { slug:"vgz", name:"VGZ", sector:"zorgverzekeraar", hq:"arnhem", verified:false,
    reorg:"Coöperatieve verzekeraars stroomlijnen hun processen en teams om de premies betaalbaar te houden.",
    tone:"Je werkte voor het collectief, laat nu iemand naast jóu staan." },
  { slug:"cz", name:"CZ", sector:"zorgverzekeraar", hq:"tilburg", verified:false,
    reorg:"Grote zorgverzekeraars automatiseren klantprocessen, waardoor bepaalde functies overbodig worden.",
    tone:"Je regelde de zorg voor duizenden, regel nu je eigen volgende stap goed." },
  { slug:"brunel", name:"Brunel", sector:"detachering & engineering", hq:"amsterdam", verified:false,
    reorg:"Detacheerders bewegen direct mee met de vraag van opdrachtgevers; koelt de markt af, dan krimpt de bezetting.",
    tone:"Je bracht anderen aan het werk, en nu ben jij zelf aan zet." },
  { slug:"conclusion", name:"Conclusion", sector:"IT-dienstverlening", hq:"utrecht", verified:false,
    reorg:"IT-dienstverleners herschikken teams zodra klantopdrachten en technologiekeuzes verschuiven.",
    tone:"Je loste de vraagstukken van anderen op, tijd voor een goede oplossing voor jezelf." },
  { slug:"cognizant-nederland", name:"Cognizant Nederland", sector:"IT-dienstverlening", hq:"amsterdam", verified:false,
    reorg:"Internationale IT-dienstverleners passen hun landenteams aan bij aflopende contracten en verschuivende budgetten.",
    tone:"Je hield de systemen van klanten draaiend, en toch verandert je eigen situatie plots." },
  { slug:"stork", name:"Stork", sector:"industriële dienstverlening", hq:"utrecht", verified:false,
    reorg:"Onderhouds- en industriebedrijven bewegen mee met investeringscycli in de industrie, wat de bezetting laat schommelen.",
    tone:"Je hield fabrieken draaiend, en nu staat je eigen loopbaan even stil." },
  { slug:"damen-shipyards", name:"Damen Shipyards", sector:"scheepsbouw & maritiem", hq:"dordrecht", verified:false,
    reorg:"Scheepsbouwers zijn afhankelijk van orderportefeuilles; tussen grote opdrachten door verandert de personeelsbehoefte.",
    tone:"Je bouwde schepen die de wereld over gaan, zet nu koers uit voor jezelf." },
  { slug:"bosch-nederland", name:"Bosch Nederland", sector:"techniek & maakindustrie", hq:"deventer", verified:false,
    reorg:"Internationale techniekconcerns verschuiven productie en ontwikkeling, waardoor Nederlandse functies kunnen vervallen.",
    tone:"Je stond voor degelijke techniek, en toch voelt je eigen grond nu onvast." },
  { slug:"huisman", name:"Huisman", sector:"maritieme & hijstechniek", hq:"schiedam", verified:false,
    reorg:"Bouwers van zware hijs- en offshoretechniek volgen wereldwijde projectcycli, met pieken en dalen in de bezetting.",
    tone:"Je maakte het onmogelijke tilbaar, laat je eigen situatie nu niet te zwaar worden." },
  { slug:"nobian", name:"Nobian", sector:"chemie & industrie", hq:"amsterdam", verified:false,
    reorg:"De chemie is energieprijs- en conjunctuurgevoelig; bij tegenwind worden productie en staf herzien.",
    tone:"Je werkte met de bouwstenen van de industrie, en nu verschuift je eigen fundament." },
  { slug:"nouryon", name:"Nouryon", sector:"specialty chemicals", hq:"amsterdam", verified:false,
    reorg:"Chemieconcerns herstructureren na afsplitsingen en overnames, waarbij staffuncties onder druk staan.",
    tone:"Je zorgde voor de chemie achter alledaagse producten, zorg nu voor je eigen toekomst." },
  { slug:"oci", name:"OCI", sector:"chemie & kunstmest", hq:"sittard-geleen", verified:false,
    reorg:"Kunstmest- en chemiebedrijven zijn sterk afhankelijk van gasprijzen; bij hoge kosten volgt herstructurering.",
    tone:"Je werkte in het Limburgse chemiehart, en nu verandert de grond onder je voeten." },
  { slug:"vopak", name:"Vopak", sector:"tankopslag & haven", hq:"rotterdam", verified:false,
    reorg:"Opslag- en havenbedrijven optimaliseren hun terminals en organisatie mee met de energietransitie.",
    tone:"Je bewaakte de stromen door de haven, houd nu je eigen koers vast." },
  { slug:"dow-benelux", name:"Dow Benelux", sector:"chemie & industrie", hq:"terneuzen", verified:false,
    reorg:"De basischemie in Zeeuws-Vlaanderen is sterk afhankelijk van energieprijzen en wereldwijde vraag; bij tegenwind volgt herstructurering.",
    tone:"Je hoorde bij de grootste werkgever van de regio, en nu voelt zelfs die grond onvast." },
  { slug:"yara-sluiskil", name:"Yara Sluiskil", sector:"kunstmest & chemie", hq:"terneuzen", verified:false,
    reorg:"Kunstmestproducenten zijn extreem gasprijsgevoelig; bij hoge kosten worden productie en bezetting teruggeschroefd.",
    tone:"Je hielp de wereld voeden, zorg nu dat je eigen toekomst gevoed blijft." },
  { slug:"lyondellbasell", name:"LyondellBasell", sector:"chemie & kunststoffen", hq:"rotterdam", verified:false,
    reorg:"Petrochemische bedrijven in de Rotterdamse haven passen hun organisatie aan bij marges die onder druk staan.",
    tone:"Je werkte aan de grondstoffen van alledag, en nu verandert je eigen situatie." },
  { slug:"nexperia", name:"Nexperia", sector:"halfgeleiders", hq:"nijmegen", verified:false,
    reorg:"Chipfabrikanten bewegen mee met de grillige halfgeleidermarkt en geopolitieke spanningen, wat de bezetting raakt.",
    tone:"Je maakte de chips die overal in zitten, en toch is je eigen plek nu onzeker." },
  { slug:"besi", name:"Besi", sector:"halfgeleidermachines", hq:"arnhem", verified:false,
    reorg:"Toeleveranciers van chipmachines zijn cyclisch; na topjaren volgen correcties in de personeelsbehoefte.",
    tone:"Je bouwde aan de machines achter de chips, tijd om je eigen koers te bepalen." },
  { slug:"asm-international", name:"ASM International", sector:"halfgeleiders", hq:"almere", verified:false,
    reorg:"Producenten van chipapparatuur schalen hun teams op en af met de investeringscycli van hun klanten.",
    tone:"Je stond aan de basis van de hightech, laat je eigen basis nu stevig zijn." },
  { slug:"prodrive-technologies", name:"Prodrive Technologies", sector:"hightech & elektronica", hq:"eindhoven", verified:false,
    reorg:"Hightechbedrijven in de Brainport-regio bewegen mee met opdrachten; valt een grote order weg, dan verandert de bezetting.",
    tone:"Je werkte aan geavanceerde techniek, en nu verandert je eigen situatie plots." },
  { slug:"sioux-technologies", name:"Sioux Technologies", sector:"hightech engineering", hq:"eindhoven", verified:false,
    reorg:"Engineeringbedrijven zijn afhankelijk van klantprojecten; koelt de vraag af, dan krimpen de teams.",
    tone:"Je loste complexe puzzels op, tijd om die van jezelf goed op te lossen." },
  { slug:"gkn-fokker", name:"GKN Aerospace (Fokker)", sector:"lucht- & ruimtevaart", hq:"hoogeveen", verified:false,
    reorg:"De lucht- en ruimtevaartindustrie is programmagevoelig; tussen grote projecten door verschuift de personeelsbehoefte.",
    tone:"Je bouwde aan wat de lucht in ging, houd nu je eigen voeten stevig op de grond." },
  { slug:"aalberts", name:"Aalberts", sector:"industriële technologie", hq:"utrecht", verified:false,
    reorg:"Industriële concerns herstructureren geregeld hun bedrijfsonderdelen na overnames en afstotingen.",
    tone:"Je hoorde bij een breed industrieconcern, en nu draait het even om jou." },
  { slug:"nedschroef", name:"Nedschroef", sector:"metaal & bevestigingstechniek", hq:"helmond", verified:false,
    reorg:"Toeleveranciers van de auto- en maakindustrie zijn conjunctuurgevoelig; bij minder vraag vervallen functies.",
    tone:"Je leverde de schakels die alles bijeenhouden, zorg nu dat je eigen situatie klopt." },
  { slug:"wavin", name:"Wavin", sector:"bouwmaterialen & kunststof", hq:"zwolle", verified:false,
    reorg:"Producenten voor de bouw bewegen mee met de bouwconjunctuur; bij een dip volgt aanpassing van de organisatie.",
    tone:"Je maakte wat onder de grond het land laat werken, houd nu je eigen basis op orde." },
  { slug:"rtl-nederland", name:"RTL Nederland", sector:"media & omroep", hq:"hilversum", verified:false,
    reorg:"Omroepen en mediabedrijven reorganiseren door dalende advertentie-inkomsten en de verschuiving naar streaming.",
    tone:"Je maakte televisie voor miljoenen, en nu staat je eigen verhaal op een keerpunt." },
  { slug:"dpg-media", name:"DPG Media", sector:"media & uitgeverij", hq:"amsterdam", verified:false,
    reorg:"Uitgevers digitaliseren en fuseren titels, waardoor redactionele en ondersteunende functies verdwijnen.",
    tone:"Je bracht het nieuws bij de lezer, zorg nu dat je eigen volgende hoofdstuk klopt." },
  { slug:"talpa-network", name:"Talpa Network", sector:"media & entertainment", hq:"hilversum", verified:false,
    reorg:"Mediabedrijven schuiven mee met kijkcijfers en advertentiemarkt; bij tegenvallers wordt de organisatie ingedikt.",
    tone:"Je hoorde bij het entertainment van Nederland, en nu verandert je eigen situatie." },
  { slug:"adecco", name:"Adecco", sector:"uitzenden & HR-dienstverlening", hq:"den-bosch", verified:false,
    reorg:"Uitzenders bewegen als eerste mee met de conjunctuur; koelt de arbeidsmarkt af, dan krimpt ook de eigen organisatie.",
    tone:"Je bracht anderen aan het werk, en nu ben jij zelf aan de beurt." },
  { slug:"manpower", name:"Manpower", sector:"uitzenden & HR", hq:"amsterdam", verified:false,
    reorg:"HR-dienstverleners passen hun eigen bezetting aan zodra de vraag naar personeel bij opdrachtgevers daalt.",
    tone:"Je hielp mensen aan een baan, laat nu iemand met jou meedenken." },
  { slug:"youngcapital", name:"YoungCapital", sector:"uitzenden & recruitment", hq:"hoofddorp", verified:false,
    reorg:"Recruitmentbureaus zijn sterk conjunctuurgevoelig; bij minder vacatures verandert de personeelsbehoefte snel.",
    tone:"Je verbond mensen met kansen, tijd om je eigen kans goed te pakken." },
  { slug:"olympia", name:"Olympia", sector:"uitzenden & detachering", hq:"utrecht", verified:false,
    reorg:"Uitzendorganisaties schalen hun eigen teams op en af met de vraag op de arbeidsmarkt.",
    tone:"Je regelde werk voor anderen, regel nu je eigen deal met zorg." },
  { slug:"transavia", name:"Transavia", sector:"luchtvaart", hq:"hoofddorp", verified:false,
    reorg:"Luchtvaartmaatschappijen passen hun organisatie aan bij schommelende vraag, brandstofprijzen en vlootkeuzes.",
    tone:"Je bracht mensen op reis, zet nu zelf een goede volgende stap." },
  { slug:"uwv", name:"UWV", sector:"overheid & uitvoering", hq:"amsterdam", verified:false,
    reorg:"Ook uitvoeringsorganisaties reorganiseren: digitalisering en politieke keuzes veranderen taken, waardoor functies verdwijnen of verschuiven.",
    tone:"Je hielp anderen aan hun recht op een uitkering, nu telt jouw eigen situatie." },
  { slug:"belastingdienst", name:"Belastingdienst", sector:"overheid & fiscaal", hq:"den-haag", verified:false,
    reorg:"De Belastingdienst hervormt en automatiseert al jaren; bij reorganisaties en afsplitsingen veranderen functies ingrijpend.",
    tone:"Je stond voor de publieke zaak, zorg nu dat je eigen zaak goed geregeld is." },
  { slug:"prorail", name:"ProRail", sector:"spoor & infrastructuur", hq:"utrecht", verified:false,
    reorg:"Semipublieke infrabeheerders herzien hun organisatie bij veranderende budgetten en politieke keuzes.",
    tone:"Je hield het spoor veilig, houd nu ook je eigen route helder." },
  { slug:"rijkswaterstaat", name:"Rijkswaterstaat", sector:"overheid & infrastructuur", hq:"utrecht", verified:false,
    reorg:"Grote uitvoeringsdiensten stroomlijnen hun organisatie mee met opgaven en bezuinigingen.",
    tone:"Je zorgde dat het land droog en bereikbaar bleef, zorg nu voor je eigen zekerheid." },
  { slug:"gemeente-amsterdam", name:"Gemeente Amsterdam", sector:"overheid & bestuur", hq:"amsterdam", verified:false,
    reorg:"Gemeenten reorganiseren bij bezuinigingen en veranderende taken; ook ambtenaren krijgen dan een beëindigingsvoorstel.",
    tone:"Je werkte voor de stad, laat de stad nu ook eerlijk voor jou zijn." },
  { slug:"amsterdam-umc", name:"Amsterdam UMC", sector:"zorg & ziekenhuis", hq:"amsterdam", verified:false,
    reorg:"Ziekenhuizen staan onder financiële druk en reorganiseren ondersteunende en staffuncties, ook als de zorg zelf doorgaat.",
    tone:"Je zorgde voor anderen, nu is het tijd dat iemand voor jou zorgt." },
  { slug:"erasmus-mc", name:"Erasmus MC", sector:"zorg & ziekenhuis", hq:"rotterdam", verified:false,
    reorg:"Academische ziekenhuizen herzien hun organisatie bij krappe budgetten en veranderende zorgvraag.",
    tone:"Je stond aan het bed en achter de schermen, zorg nu goed voor je eigen toekomst." },
  { slug:"umc-utrecht", name:"UMC Utrecht", sector:"zorg & ziekenhuis", hq:"utrecht", verified:false,
    reorg:"Ook grote UMC's reorganiseren staf- en ondersteuningsafdelingen om de zorg betaalbaar te houden.",
    tone:"Je hielp mensen beter worden, laat nu iemand met jou meedenken." },
  { slug:"radboudumc", name:"Radboudumc", sector:"zorg & ziekenhuis", hq:"nijmegen", verified:false,
    reorg:"Ziekenhuizen bezuinigen op overhead en ondersteuning, waardoor niet-zorgfuncties onder druk staan.",
    tone:"Je gaf het beste van jezelf voor de patiënt, kom nu op voor jezelf." },
  { slug:"parnassia-groep", name:"Parnassia Groep", sector:"geestelijke gezondheidszorg", hq:"den-haag", verified:false,
    reorg:"GGZ-instellingen kampen met financiële druk en personeelstekorten, wat leidt tot reorganisaties in staf en overhead.",
    tone:"Je hielp mensen met hun geest, houd nu je eigen rust vast." },
  { slug:"universiteit-van-amsterdam", name:"Universiteit van Amsterdam", sector:"onderwijs & wetenschap", hq:"amsterdam", verified:false,
    reorg:"Universiteiten reorganiseren bij dalende studentenaantallen en bezuinigingen op onderwijs en onderzoek.",
    tone:"Je droeg kennis over, gebruik die scherpte nu voor je eigen situatie." },
  { slug:"tu-delft", name:"TU Delft", sector:"onderwijs & wetenschap", hq:"delft", verified:false,
    reorg:"Ook technische universiteiten passen hun organisatie aan bij veranderende financiering en studentaantallen.",
    tone:"Je werkte aan de techniek van morgen, zet nu een goede stap voor jezelf." },
  { slug:"universiteit-utrecht", name:"Universiteit Utrecht", sector:"onderwijs & wetenschap", hq:"utrecht", verified:false,
    reorg:"Bezuinigingen in het hoger onderwijs raken zowel wetenschappelijke als ondersteunende functies.",
    tone:"Je bracht studenten verder, laat nu iemand jóu verder helpen." },
  { slug:"rijksuniversiteit-groningen", name:"Rijksuniversiteit Groningen", sector:"onderwijs & wetenschap", hq:"groningen", verified:false,
    reorg:"Universiteiten in krimpregio's voelen dalende studentenaantallen extra, met reorganisaties tot gevolg.",
    tone:"Je was een baken van kennis in het noorden, houd nu je eigen koers vast." },
  { slug:"fontys", name:"Fontys Hogescholen", sector:"onderwijs & hbo", hq:"eindhoven", verified:false,
    reorg:"Hogescholen herzien hun opleidingen en organisatie bij veranderende instroom en bekostiging.",
    tone:"Je leidde een nieuwe generatie op, tijd om je eigen volgende stap te zetten." }
];

// ---------------------------------------------------------------------------
// STEDEN — lokale hulp-pagina's. rechtbank = bevoegd arrondissement (kanton).
// ---------------------------------------------------------------------------
const cities = [
  { slug:"amsterdam", name:"Amsterdam", province:"Noord-Holland", court:"rechtbank Amsterdam",
    local:"Amsterdam is het financiële en technologische hart van Nederland, met hoofdkantoren van banken, verzekeraars en grote techbedrijven. Juist daar spelen de reorganisaties van 2026 het hevigst." },
  { slug:"rotterdam", name:"Rotterdam", province:"Zuid-Holland", court:"rechtbank Rotterdam",
    local:"Rotterdam draait op haven, logistiek, maakindustrie en zakelijke dienstverlening. Een praktische stad waar mensen niet snel klagen, maar wél recht hebben op een eerlijke deal." },
  { slug:"den-haag", name:"Den Haag", province:"Zuid-Holland", court:"rechtbank Den Haag",
    local:"Den Haag is de stad van overheid, semi-publieke instellingen en internationale organisaties. Ontslag heeft hier vaak eigen, bovenwettelijke regelingen." },
  { slug:"utrecht", name:"Utrecht", province:"Utrecht", court:"rechtbank Midden-Nederland",
    local:"Utrecht ligt centraal en herbergt veel hoofdkantoren van banken, verzekeraars en dienstverleners. Een knooppunt waar reorganisaties vaak beginnen." },
  { slug:"eindhoven", name:"Eindhoven", province:"Noord-Brabant", court:"rechtbank Oost-Brabant",
    local:"Eindhoven is het kloppend hart van de Brainport-regio, met ASML, NXP en talloze hightech-toeleveranciers. Als daar wordt gereorganiseerd, voelt de hele regio het." },
  { slug:"veldhoven", name:"Veldhoven", province:"Noord-Brabant", court:"rechtbank Oost-Brabant",
    local:"Veldhoven staat wereldwijd op de kaart door ASML. Voor veel inwoners is hun baan en hypotheek direct verbonden met de hightech-sector." },
  { slug:"amersfoort", name:"Amersfoort", province:"Utrecht", court:"rechtbank Midden-Nederland",
    local:"Amersfoort is een groeiende zakelijke stad met veel dienstverlenende en financiële werkgevers, centraal in het land gelegen." },
  { slug:"arnhem", name:"Arnhem", province:"Gelderland", court:"rechtbank Gelderland",
    local:"Arnhem combineert energie, zorg en zakelijke dienstverlening. Een regio met stevige cao's en veel werknemers in loondienst." },
  { slug:"nijmegen", name:"Nijmegen", province:"Gelderland", court:"rechtbank Gelderland",
    local:"Nijmegen kent een sterke zorg-, onderwijs- en kennissector rond onder meer de universiteit en ziekenhuizen." },
  { slug:"tilburg", name:"Tilburg", province:"Noord-Brabant", court:"rechtbank Zeeland-West-Brabant",
    local:"Tilburg is een stad van logistiek, industrie en onderwijs, met veel werknemers in productie en dienstverlening." },
  { slug:"breda", name:"Breda", province:"Noord-Brabant", court:"rechtbank Zeeland-West-Brabant",
    local:"Breda huisvest logistiek, food en zakelijke dienstverlening, strategisch gelegen tussen de Randstad en België." },
  { slug:"den-bosch", name:"'s-Hertogenbosch", province:"Noord-Brabant", court:"rechtbank Oost-Brabant",
    local:"'s-Hertogenbosch is een bestuurlijk en zakelijk centrum van Brabant, met verzekeraars en dienstverleners als grote werkgevers." },
  { slug:"groningen", name:"Groningen", province:"Groningen", court:"rechtbank Noord-Nederland",
    local:"Groningen leunt op zorg, onderwijs, energie en de publieke sector. In het noorden telt elke baan zwaar." },
  { slug:"zwolle", name:"Zwolle", province:"Overijssel", court:"rechtbank Overijssel",
    local:"Zwolle is een groeiende werkgelegenheidsregio met zorg, onderwijs en zakelijke dienstverlening." },
  { slug:"enschede", name:"Enschede", province:"Overijssel", court:"rechtbank Overijssel",
    local:"Enschede kent een sterke maak- en kennisindustrie rond Twente, met veel technische functies." },
  { slug:"haarlem", name:"Haarlem", province:"Noord-Holland", court:"rechtbank Noord-Holland",
    local:"Haarlem ligt in de directe invloedssfeer van Amsterdam, met veel forensen in financiële en zakelijke functies." },
  { slug:"almere", name:"Almere", province:"Flevoland", court:"rechtbank Midden-Nederland",
    local:"Almere is een jonge, snelgroeiende stad met veel werknemers in dienstverlening, retail en logistiek." },
  { slug:"apeldoorn", name:"Apeldoorn", province:"Gelderland", court:"rechtbank Gelderland",
    local:"Apeldoorn is een bekend centrum voor verzekeraars en de publieke sector, met veel kantoorfuncties." },
  { slug:"leiden", name:"Leiden", province:"Zuid-Holland", court:"rechtbank Den Haag",
    local:"Leiden draait op kennis, life sciences en onderwijs, met een hoogopgeleide beroepsbevolking." },
  { slug:"maastricht", name:"Maastricht", province:"Limburg", court:"rechtbank Limburg",
    local:"Maastricht is een internationaal georiënteerde stad met onderwijs, zorg en grensoverschrijdend werk." },
  { slug:"delft", name:"Delft", province:"Zuid-Holland", court:"rechtbank Den Haag",
    local:"Delft is een kennis- en hightech-stad rond de technische universiteit, met veel innovatieve bedrijven en hoogopgeleide werknemers." },
  { slug:"hilversum", name:"Hilversum", province:"Noord-Holland", court:"rechtbank Midden-Nederland",
    local:"Hilversum is het mediacentrum van Nederland, met omroepen en productiebedrijven waar reorganisaties en flexibele contracten aan de orde van de dag zijn." },
  { slug:"leeuwarden", name:"Leeuwarden", province:"Friesland", court:"rechtbank Noord-Nederland",
    local:"Leeuwarden leunt op zorg, onderwijs, agrofood en de publieke sector. In het noorden weegt het verlies van een baan extra zwaar." },
  { slug:"deventer", name:"Deventer", province:"Overijssel", court:"rechtbank Overijssel",
    local:"Deventer combineert industrie, uitgeverij en dienstverlening, met veel werknemers in productie en kantoorfuncties." },
  { slug:"hengelo", name:"Hengelo", province:"Overijssel", court:"rechtbank Overijssel",
    local:"Hengelo vormt met Enschede het hart van de Twentse maakindustrie, met veel technische en productiefuncties." },
  { slug:"ede", name:"Ede", province:"Gelderland", court:"rechtbank Gelderland",
    local:"Ede is een groeiende werkgelegenheidsregio met food, defensie en logistiek als belangrijke sectoren." },
  { slug:"alkmaar", name:"Alkmaar", province:"Noord-Holland", court:"rechtbank Noord-Holland",
    local:"Alkmaar is een regionaal centrum voor handel, zorg en dienstverlening in Noord-Holland-Noord." },
  { slug:"dordrecht", name:"Dordrecht", province:"Zuid-Holland", court:"rechtbank Rotterdam",
    local:"Dordrecht heeft een sterke maritieme en industriële traditie, met veel werknemers in techniek en logistiek." },
  { slug:"zoetermeer", name:"Zoetermeer", province:"Zuid-Holland", court:"rechtbank Den Haag",
    local:"Zoetermeer is een ICT- en dienstverleningsstad tussen Den Haag en de Randstad, met veel kantoorfuncties." },
  { slug:"amstelveen", name:"Amstelveen", province:"Noord-Holland", court:"rechtbank Amsterdam",
    local:"Amstelveen huisvest internationale hoofdkantoren, waaronder KLM en grote adviesbureaus, met veel hoogopgeleide werknemers." },
  { slug:"hoofddorp", name:"Hoofddorp", province:"Noord-Holland", court:"rechtbank Noord-Holland",
    local:"Hoofddorp ligt in de directe invloedssfeer van Schiphol, met veel logistiek, luchtvaart en internationale bedrijven." },
  { slug:"zaandam", name:"Zaandam", province:"Noord-Holland", court:"rechtbank Noord-Holland",
    local:"Zaandam is een food- en retailregio met grote hoofdkantoren, waaronder dat van Ahold Delhaize, net boven Amsterdam." },
  { slug:"heerlen", name:"Heerlen", province:"Limburg", court:"rechtbank Limburg",
    local:"Heerlen is een bestuurlijk en financieel centrum van Zuid-Limburg, met grote werkgevers in pensioenen, zorg en overheid." },
  { slug:"emmen", name:"Emmen", province:"Drenthe", court:"rechtbank Noord-Nederland",
    local:"Emmen heeft een sterke industriële en logistieke traditie, met veel werknemers in productie en techniek." },
  { slug:"venlo", name:"Venlo", province:"Limburg", court:"rechtbank Limburg",
    local:"Venlo is een logistiek knooppunt aan de Duitse grens, met veel werkgevers in transport, handel en industrie." },
  { slug:"helmond", name:"Helmond", province:"Noord-Brabant", court:"rechtbank Oost-Brabant",
    local:"Helmond hoort bij de Brainport-regio en kent veel maakindustrie en technische werkgelegenheid." },
  { slug:"gouda", name:"Gouda", province:"Zuid-Holland", court:"rechtbank Den Haag",
    local:"Gouda combineert dienstverlening, food en zakelijke werkgevers, centraal in het Groene Hart." },
  { slug:"hoorn", name:"Hoorn", province:"Noord-Holland", court:"rechtbank Noord-Holland",
    local:"Hoorn is een regionaal centrum voor handel, zorg en dienstverlening in West-Friesland." },
  { slug:"assen", name:"Assen", province:"Drenthe", court:"rechtbank Noord-Nederland",
    local:"Assen leunt op overheid, zorg en dienstverlening. In het noorden weegt het verlies van een baan extra zwaar." },
  { slug:"roosendaal", name:"Roosendaal", province:"Noord-Brabant", court:"rechtbank Zeeland-West-Brabant",
    local:"Roosendaal is een logistiek en industrieel knooppunt tussen de Randstad en België." },
  { slug:"oss", name:"Oss", province:"Noord-Brabant", court:"rechtbank Oost-Brabant",
    local:"Oss draait op farmacie, voeding en maakindustrie, met een groot life-sciencescluster als belangrijke werkgever." },
  { slug:"sittard-geleen", name:"Sittard-Geleen", province:"Limburg", court:"rechtbank Limburg",
    local:"Sittard-Geleen is het hart van de Limburgse chemie rond Chemelot. Als daar wordt bijgestuurd, voelt de hele regio het." },
  { slug:"roermond", name:"Roermond", province:"Limburg", court:"rechtbank Limburg",
    local:"Roermond combineert retail, logistiek en maakindustrie, strategisch gelegen aan de Duitse grens." },
  { slug:"lelystad", name:"Lelystad", province:"Flevoland", court:"rechtbank Midden-Nederland",
    local:"Lelystad is een jonge stad met veel logistiek, publieke dienstverlening en groeiende bedrijvigheid in Flevoland." },
  { slug:"middelburg", name:"Middelburg", province:"Zeeland", court:"rechtbank Zeeland-West-Brabant",
    local:"Middelburg is het bestuurlijke centrum van Zeeland, met overheid, zorg en toerisme als grote werkgevers." },
  { slug:"nieuwegein", name:"Nieuwegein", province:"Utrecht", court:"rechtbank Midden-Nederland",
    local:"Nieuwegein huisvest veel zakelijke dienstverlening en IT-bedrijven, pal naast de knooppuntstad Utrecht." },
  { slug:"alphen-aan-den-rijn", name:"Alphen aan den Rijn", province:"Zuid-Holland", court:"rechtbank Den Haag",
    local:"Alphen aan den Rijn ligt in het Groene Hart en leunt op logistiek, maakindustrie en dienstverlening." },
  { slug:"schiedam", name:"Schiedam", province:"Zuid-Holland", court:"rechtbank Rotterdam",
    local:"Schiedam grenst aan Rotterdam en kent een sterke maritieme maakindustrie en haventoelevering." },
  { slug:"doetinchem", name:"Doetinchem", province:"Gelderland", court:"rechtbank Gelderland",
    local:"Doetinchem is een economisch centrum van de Achterhoek, met veel maakindustrie, zorg en familiebedrijven." },
  { slug:"heerenveen", name:"Heerenveen", province:"Friesland", court:"rechtbank Noord-Nederland",
    local:"Heerenveen combineert maakindustrie, sport en dienstverlening en is een economische motor van Fryslân." },
  { slug:"terneuzen", name:"Terneuzen", province:"Zeeland", court:"rechtbank Zeeland-West-Brabant",
    local:"Terneuzen is het industriële hart van Zeeuws-Vlaanderen, met een groot chemie- en havencluster als bepalende werkgever." },
  { slug:"hoogeveen", name:"Hoogeveen", province:"Drenthe", court:"rechtbank Noord-Nederland",
    local:"Hoogeveen combineert maakindustrie, lucht- en ruimtevaarttoelevering en logistiek in het hart van Drenthe." }
];

// ---------------------------------------------------------------------------
// SCENARIO'S — situationele pagina's met echte juridische inhoud.
// ---------------------------------------------------------------------------
const scenarios = [
  { slug:"reorganisatie", h1:"Vaststellingsovereenkomst bij een reorganisatie",
    intro:"Je functie vervalt door een reorganisatie en er ligt ineens een vaststellingsovereenkomst op tafel. Dat voelt onpersoonlijk, alsof je een nummer bent. Maar juist bij een reorganisatie sta je vaak sterker dan je denkt.",
    body:"Bij bedrijfseconomisch ontslag moet je werkgever meestal het afspiegelingsbeginsel volgen om te bepalen wie boventallig wordt. Wordt dat niet zorgvuldig gedaan, dan is je ontslag mogelijk niet houdbaar. Bovendien geldt er bij grote reorganisaties vaak een sociaal plan met een vergoeding boven de wettelijke transitievergoeding.",
    risk:"Het grootste risico is dat je akkoord gaat met het eerste bod zonder te weten wat het sociaal plan of de markt eigenlijk toestaat.",
    check:["Is de afspiegeling correct toegepast?","Geldt er een sociaal plan met een hogere vergoeding?","Word je vrijgesteld van werk tot de einddatum?","Is je WW volledig veiliggesteld?"] },
  { slug:"boventallig-verklaard", h1:"Boventallig verklaard: wat moet je nu doen?",
    intro:"'Je bent boventallig.' Weinig zinnen komen zo hard aan. Je hoofd tolt, en er wordt van je verwacht dat je snel tekent. Doe dat niet.",
    body:"Boventalligheid betekent dat je arbeidsplaats vervalt, niet dat je slecht functioneert. Je werkgever moet eerst kijken of er een passende functie is en de juiste selectieregels toepassen. Pas daarna komt een vaststellingsovereenkomst in beeld, en die is onderhandelbaar.",
    risk:"Onder tijdsdruk tekenen is de grootste valkuil. Je hebt altijd bedenktijd en bijna altijd onderhandelingsruimte.",
    check:["Klopt de reden en de selectie?","Is er gezocht naar een passende functie?","Is de vergoeding marktconform?","Blijft je WW-recht overeind?"] },
  { slug:"tijdens-ziekte", h1:"Vaststellingsovereenkomst tijdens ziekte: teken dit nooit zomaar",
    intro:"Ziek zijn én een beëindigingsvoorstel krijgen is dubbel zwaar. En het is juist nu extra belangrijk om niets te tekenen zonder advies.",
    body:"Tijdens ziekte geldt een opzegverbod, en tekenen kan zowel je Ziektewet- als je WW-rechten raken. Het UWV kan een uitkering weigeren als je meewerkt aan je ontslag terwijl je ziek bent. Alleen in specifieke situaties, bijvoorbeeld binnen een sociaal plan, kan het verantwoord zijn.",
    risk:"Het risico is groot: je kunt zowel je loondoorbetaling bij ziekte als je uitkering kwijtraken.",
    check:["Geldt er een opzegverbod tijdens ziekte?","Behoud je je Ziektewet-rechten?","Is de re-integratie correct doorlopen?","Wat zegt de bedrijfsarts?"] },
  { slug:"zwangerschap", h1:"Vaststellingsovereenkomst tijdens zwangerschap",
    intro:"Een beëindigingsvoorstel terwijl je zwanger bent of net bevallen. Dat mag lang niet altijd, en je verdient bescherming.",
    body:"Tijdens zwangerschap en het bevallingsverlof geldt een bijzonder opzegverbod. Meewerken aan ontslag kan je rechten aantasten. Er mag bovendien geen sprake zijn van discriminatie op grond van zwangerschap; is dat wel zo, dan sta je juridisch sterk.",
    risk:"Je kunt onbedoeld bescherming en uitkeringsrechten opgeven, of een verboden onderscheid over het hoofd zien.",
    check:["Geldt het opzegverbod voor jouw situatie?","Is er sprake van discriminatie?","Blijven je verlofrechten in stand?","Is je WW veilig na het verlof?"] },
  { slug:"concurrentiebeding", h1:"Vaststellingsovereenkomst en je concurrentiebeding",
    intro:"Je wilt verder in je vak, maar een concurrentiebeding houdt je tegen. Bij een vertrekregeling is dat bij uitstek onderhandelbaar.",
    body:"Als je werkgever afscheid van je neemt, is het vaak onredelijk om je daarna aan een concurrentiebeding te houden. Laat in de vaststellingsovereenkomst vastleggen dat het beding vervalt of wordt beperkt. Ook een relatiebeding en geheimhouding horen expliciet geregeld te worden.",
    risk:"Vergeet je het beding te regelen, dan zit je er na je vertrek alsnog aan vast en beperk je je eigen toekomst.",
    check:["Vervalt het concurrentiebeding?","Wat gebeurt er met het relatiebeding?","Zijn er afspraken over geheimhouding?","Mag je je netwerk meenemen?"] },
  { slug:"oudere-werknemer", h1:"Vaststellingsovereenkomst als 60-plusser",
    intro:"Dichter bij je pensioen ontslagen worden voelt oneerlijk, en financieel is de inzet hoog. Elke euro en elke maand telt nu extra.",
    body:"Voor oudere werknemers is de weg naar nieuw werk vaak langer, en het inkomensgat tot de AOW groter. Let daarom scherp op de hoogte van de vergoeding, de aansluiting op WW en eventueel de mogelijkheid om richting pensioen te overbruggen. Soms zijn er specifieke regelingen voor oudere werknemers.",
    risk:"Het risico is een jarenlang inkomensgat tot je pensioen als de vergoeding en WW niet goed op elkaar aansluiten.",
    check:["Overbrugt de vergoeding tot je AOW of pensioen?","Sluit de WW naadloos aan?","Is er een regeling voor oudere werknemers?","Klopt de fictieve opzegtermijn?"] },
  { slug:"disfunctioneren", h1:"Vaststellingsovereenkomst bij vermeend disfunctioneren",
    intro:"Je werkgever zegt dat je onvoldoende functioneert, maar zo voelt het voor jou niet. Laat je niet zomaar een verhaal opdringen dat je WW kan kosten.",
    body:"Voor ontslag wegens disfunctioneren gelden strenge eisen: een duidelijk verbetertraject, dossieropbouw en een reële kans om je te verbeteren. Ontbreekt dat, dan sta je sterk. In de vaststellingsovereenkomst moet de reden bovendien neutraal zijn, zodat je WW-recht niet in gevaar komt.",
    risk:"Als 'disfunctioneren' als verwijtbare reden in de overeenkomst komt, kan het UWV je WW weigeren.",
    check:["Is er een echt verbetertraject geweest?","Klopt de dossieropbouw?","Staat er een neutrale ontslaggrond in?","Blijft je WW veilig?"] },
  { slug:"verstoorde-arbeidsrelatie", h1:"Vaststellingsovereenkomst bij een verstoorde arbeidsrelatie",
    intro:"Er is iets onherstelbaar geknapt tussen jou en je werkgever. Vervelend, maar het kan wél leiden tot een nette, veilige vertrekregeling.",
    body:"Een verstoorde arbeidsverhouding is een geldige, neutrale grond voor beëindiging met behoud van WW. Het is belangrijk dat de schuldvraag niet bij jou wordt neergelegd. Vaak is er ruimte om over vergoeding, vrijstelling en een goed getuigschrift te onderhandelen.",
    risk:"Wordt de verstoring aan jou toegerekend, dan kan dat zowel je uitkering als je reputatie schaden.",
    check:["Is de grond neutraal geformuleerd?","Ligt de schuld niet bij jou?","Krijg je een positief getuigschrift?","Is er vrijstelling van werk?"] },
  { slug:"na-overname-of-fusie", h1:"Vaststellingsovereenkomst na een overname of fusie",
    intro:"Na een fusie of overname verandert alles, en jouw functie past er ineens niet meer in. Je rechten veranderen echter niet zomaar.",
    body:"Bij een overgang van onderneming behoud je in principe je rechten en arbeidsvoorwaarden. Verandert je functie of vervalt die na de reorganisatie die vaak op een fusie volgt, dan gelden de normale regels voor bedrijfseconomisch ontslag, inclusief afspiegeling en een eerlijke vergoeding.",
    risk:"Het risico is dat verworven rechten en anciënniteit onder tafel verdwijnen in de drukte van de integratie.",
    check:["Zijn je verworven rechten meegenomen?","Telt je volledige diensttijd mee?","Klopt de vergoeding en afspiegeling?","Is je WW veilig?"] },
  { slug:"ontslag-door-ai", h1:"Ontslag omdat je werk wordt geautomatiseerd of door AI wordt overgenomen",
    intro:"Steeds vaker verdwijnen functies omdat AI of automatisering het werk overneemt. Het klinkt als vooruitgang, maar voor jou voelt het als een koude douche. Je rechten blijven precies hetzelfde.",
    body:"Of je functie nu vervalt door een klassieke reorganisatie of door AI, juridisch geldt hetzelfde: het is bedrijfseconomisch ontslag. De werkgever moet de afspiegeling en selectieregels volgen, en je hebt recht op een eerlijke vergoeding en een veilige WW. Automatisering is geen reden om minder te bieden.",
    risk:"Bedrijven verkopen zo'n reorganisatie graag als 'innovatie' en hopen dat je zonder tegenspraak tekent.",
    check:["Is het echt bedrijfseconomisch onderbouwd?","Is de afspiegeling juist?","Is de vergoeding marktconform?","Blijft je WW-recht overeind?"] },
  { slug:"tijdelijk-contract-niet-verlengd", h1:"Vaststellingsovereenkomst bij een aflopend tijdelijk contract",
    intro:"Je tijdelijke contract loopt af en toch krijg je een vaststellingsovereenkomst voorgelegd. Dat roept vragen op, want waarom zou je die tekenen?",
    body:"Bij een aflopend tijdelijk contract is een vaststellingsovereenkomst meestal niet nodig en kan die zelfs nadelig zijn. Soms wil de werkgever ermee eerder afscheid nemen dan de einddatum. Beoordeel altijd of tekenen je iets oplevert of juist rechten kost, zoals de transitievergoeding of loon tot de einddatum.",
    risk:"Je kunt loon, transitievergoeding of WW-opbouw mislopen door onnodig te tekenen.",
    check:["Levert tekenen jou iets op?","Behoud je je transitievergoeding?","Krijg je loon tot de oorspronkelijke einddatum?","Is je WW veilig?"] },
  { slug:"vrijstelling-van-werk", h1:"Vrijstelling van werk in je vaststellingsovereenkomst",
    intro:"Nog maanden doorwerken terwijl iedereen weet dat je vertrekt? Dat hoeft vaak niet. Vrijstelling van werk is een waardevol onderhandelpunt.",
    body:"In veel vertrekregelingen word je vrijgesteld van werk met behoud van salaris tot de einddatum. Zo kun je direct op zoek naar iets nieuws. Let op afspraken over vakantiedagen, opgebouwd verlof en of de vrijstelling onherroepelijk is, zodat je niet alsnog kunt worden teruggeroepen.",
    risk:"Zonder heldere afspraken kun je worden teruggeroepen of verlies je opgebouwde vakantiedagen.",
    check:["Is de vrijstelling onherroepelijk?","Behoud je je volledige salaris?","Wat gebeurt er met je vakantiedagen?","Mag je alvast elders beginnen?"] },
  { slug:"finale-kwijting", h1:"Finale kwijting in je vaststellingsovereenkomst: waar teken je precies voor?",
    intro:"Onderaan bijna elke vaststellingsovereenkomst staat 'finale kwijting'. Klein zinnetje, grote gevolgen. Het betekent dat je na tekenen niets meer kunt claimen.",
    body:"Met finale kwijting verklaren jij en je werkgever dat jullie na afwikkeling niets meer van elkaar te vorderen hebben. Daarom is het cruciaal dat álles wat jou toekomt eerst goed is geregeld: je vergoeding, openstaande vakantiedagen, bonus, dertiende maand, onkosten en pensioen. Wat je vergeet, ben je daarna kwijt.",
    risk:"Je tekent per ongeluk je recht op een bonus, overuren of vakantiedagen weg omdat die niet apart zijn benoemd.",
    check:["Zijn al je vergoedingen en dagen uitbetaald of benoemd?","Is je pensioen correct afgehandeld?","Zijn onkosten en overuren meegenomen?","Wat valt buiten de finale kwijting?"] },
  { slug:"transitievergoeding-onderhandelen", h1:"Meer dan de transitievergoeding: zo onderhandel je je bod omhoog",
    intro:"Het eerste bod van je werkgever is bijna nooit het beste. Bij een vaststellingsovereenkomst is de wettelijke transitievergoeding je bodem, niet je plafond.",
    body:"Omdat een VSO een onderhandeling is, kun je vragen om meer dan de wettelijke vergoeding, bijvoorbeeld een hogere factor, een langere opzegtermijn met behoud van salaris, een vergoeding voor scholing of outplacement, of het laten vervallen van een concurrentiebeding. Een goede specialist weet wat in jouw situatie en sector realistisch is.",
    risk:"Uit onzekerheid akkoord gaan met het eerste bod kost je zomaar duizenden euro's.",
    check:["Is het bod marktconform voor jouw sector?","Kun je een hogere factor onderhandelen?","Zit er budget voor scholing of outplacement in?","Vervalt je concurrentiebeding?"] },
  { slug:"getuigschrift-en-referenties", h1:"Getuigschrift en referenties in je vaststellingsovereenkomst",
    intro:"Hoe over je vertrek wordt gesproken, bepaalt mede je volgende stap. Leg daarom vast wat je werkgever over je zegt.",
    body:"Je kunt in de vaststellingsovereenkomst afspraken maken over een positief getuigschrift, een neutrale of positieve referentie en een gezamenlijke boodschap richting collega's en de buitenwereld. Zo houd je de regie over je reputatie en start je met een schone lei bij je volgende werkgever.",
    risk:"Zonder afspraken loop je het risico op een lauwe of negatieve referentie die je nieuwe baan in de weg zit.",
    check:["Krijg je een positief getuigschrift?","Wat is de afgesproken referentie?","Is er een gezamenlijke communicatielijn?","Mag je zelf bepalen wat je deelt?"] },
  { slug:"vso-en-belasting", h1:"Vaststellingsovereenkomst en belasting: houd je netto over wat je denkt?",
    intro:"Een mooi brutobedrag op papier is niet hetzelfde als wat er op je rekening komt. De fiscus kijkt mee, en dat verandert het plaatje.",
    body:"Je ontslagvergoeding is belast als loon uit vroegere dienstbetrekking, waardoor je er belasting over betaalt in het jaar van uitkering. Soms kun je fiscaal slim spreiden of de vergoeding op een gunstiger moment laten uitkeren. Het is verstandig om vóór het tekenen te weten wat je netto overhoudt, zodat je met echte cijfers onderhandelt.",
    risk:"Je baseert je beslissing op een brutobedrag en komt netto bedrogen uit.",
    check:["Weet je wat je netto overhoudt?","Kan de vergoeding fiscaal gunstig worden getimed?","Is er ruimte voor een spreiding?","Zijn er onbelaste componenten mogelijk?"] },
  { slug:"na-lang-dienstverband", h1:"Vaststellingsovereenkomst na een lang dienstverband",
    intro:"Twintig, dertig jaar bij dezelfde werkgever, en dan dit. Na zo'n lang dienstverband is een vertrek extra beladen, en staat er financieel veel op het spel.",
    body:"Bij een lang dienstverband is je transitievergoeding hoger en weegt je opgebouwde anciënniteit zwaar. Tegelijk is de weg naar nieuw werk soms langer. Let daarom scherp op de hoogte van de vergoeding, een eerlijke waardering van je jaren, en een goede overgang naar WW of ander werk. Loyaliteit mag beloond worden, niet afgestraft.",
    risk:"Je jarenlange inzet wordt niet vertaald in een passende vergoeding en zachte landing.",
    check:["Telt je volledige diensttijd mee?","Is de vergoeding passend bij je jaren?","Is er hulp bij het vinden van nieuw werk?","Sluit je WW naadloos aan?"] }
];

// ---------------------------------------------------------------------------
// ACTUEEL — geverifieerde reorganisatiecijfers per bedrijf (bron + datum).
// Wordt getoond in een "Actueel"-blok op de bedrijfspagina. Geen officiële
// uiting van of namens het bedrijf; puur openbaar nieuws, feitelijk geciteerd.
// ---------------------------------------------------------------------------
const companyNews = {
  "asml": { fig:"≈ 1.400 banen in Nederland", text:"ASML kondigde eind januari 2026 een reorganisatie aan. Inmiddels ligt er een sociaal plan met een looptijd van twee jaar, ingegaan op 1 juni 2026.", src:"De Unie / Computable", url:"https://www.computable.nl/2026/05/12/asml-sluit-hoofdlijnen-akkoord-met-bonden/", date:"jan–mei 2026" },
  "heineken": { fig:"5.000–6.000 functies wereldwijd, waarvan ± 400 op het hoofdkantoor in Amsterdam", text:"Heineken maakte in februari 2026 bekend de komende twee jaar duizenden functies te schrappen om de organisatie te vereenvoudigen.", src:"NOS / FD", url:"", date:"feb 2026" },
  "abn-amro": { fig:"tot ≈ 5.200 banen (tot 2028)", text:"ABN AMRO schrapt de komende jaren duizenden banen om kosten te verlagen en zelfstandig te blijven.", src:"Banken.nl", url:"https://www.banken.nl/nieuws/26620/abn-amro-schrapt-5200-banen-in-strijd-voor-zelfstandigheid-en-hogere-beurswaarde", date:"2026" },
  "ing": { fig:"≈ 1.250 banen", text:"ING schrapt banen, mede door de inzet van AI, als onderdeel van een kostenbesparing van € 350 miljoen.", src:"Banken.nl", url:"https://www.banken.nl/nieuws/26953/ing-schrapt-1250-banen-mede-door-inzet-van-ai", date:"2026" },
  "philips": { fig:"≈ 1.100 banen in Nederland", text:"Philips schrapt opnieuw duizenden banen wereldwijd, waarvan een groot deel in Nederland.", src:"NOS", url:"https://nos.nl/l/2461804", date:"2026" },
  "achmea": { fig:"≈ 2.400 medewerkers geraakt", text:"Achmea kondigde een reorganisatie aan die medewerkers raakt bij merken als Zilveren Kruis, Centraal Beheer en Interpolis, vooral in productontwikkeling, distributie, communicatie en marketing.", src:"Banknieuws", url:"https://www.banknieuws.info/2026/05/verzekeraar-achmea-schrapt-350-banen.html", date:"mei 2026" },
  "zilveren-kruis": { fig:"onderdeel van de Achmea-reorganisatie (± 2.400)", text:"Bij Zilveren Kruis staan functies onder druk binnen de bredere Achmea-reorganisatie, met name in productontwikkeling, communicatie en marketing.", src:"Banknieuws", url:"https://www.banknieuws.info/2026/05/verzekeraar-achmea-schrapt-350-banen.html", date:"mei 2026" },
  "centraal-beheer": { fig:"onderdeel van de Achmea-reorganisatie (± 2.400)", text:"Ook bij Centraal Beheer vervallen functies binnen de Achmea-reorganisatie die circa 2.400 medewerkers raakt.", src:"Banknieuws", url:"https://www.banknieuws.info/2026/05/verzekeraar-achmea-schrapt-350-banen.html", date:"mei 2026" },
  "de-volksbank": { fig:"tot ≈ 950 banen (ASN Bank)", text:"Bij de Volksbank verdwijnen tot circa 950 banen als onderdeel van een breder kostenprogramma.", src:"Banken.nl", url:"https://www.banken.nl/nieuws/sector/reorganisatie", date:"2026" },
  "triodos-bank": { fig:"≈ 270 fte", text:"Triodos Bank verkleinde haar personeelsbestand met circa 270 fte, onder druk van kosten en digitalisering.", src:"Banken.nl", url:"https://www.banken.nl/nieuws/sector/reorganisatie", date:"2026" }
};

// ---------------------------------------------------------------------------
// KENNISBANK — artikelen. blocks: {h, p} of {h, list:[...]}.
// ---------------------------------------------------------------------------
const articles = [
  { slug:"reorganisatiegolf-2026", cat:"Reorganisatie", date:"2026-07-01", read:6,
    title:"De reorganisatiegolf van 2026: dit zijn je rechten bij een VSO",
    h1:"De reorganisatiegolf van 2026: dit zijn je rechten",
    desc:"In 2025 meldden 355 bedrijven een reorganisatie, het hoogste aantal in tien jaar. Wat betekent de golf van 2026 voor jou en je vaststellingsovereenkomst?",
    intro:"ASML, Heineken, ABN AMRO, ING, Philips, Achmea: de lijst met grote werkgevers die in 2026 reorganiseren wordt met de week langer. Als jij een vaststellingsovereenkomst op je bureau krijgt, is het goed om te weten dat je verre van machteloos bent.",
    blocks:[
      { h:"Waarom 2026 anders voelt", p:"In 2025 meldden 355 bedrijven een reorganisatie bij het UWV, het hoogste aantal in tien jaar en 42% meer dan het jaar ervoor. Bijna 25.000 werknemers kregen ermee te maken. De meeste meldingen kwamen uit de zakelijke dienstverlening, de metaalindustrie en de chemie. In 2026 zet die lijn door, mede aangejaagd door AI en kostenbesparingen." },
      { h:"Boventallig betekent niet dat je iets fout deed", p:"Bij een reorganisatie vervalt je functie om bedrijfseconomische redenen, niet omdat je slecht presteert. Je werkgever moet meestal het afspiegelingsbeginsel volgen: binnen vergelijkbare functies bepaalt een combinatie van leeftijdsgroepen en diensttijd wie boventallig wordt. Gaat dat niet zorgvuldig, dan sta je sterker dan je denkt." },
      { h:"Je vier belangrijkste rechten", list:["Een wettelijke bedenktermijn van 14 dagen na ondertekening (21 dagen als die termijn niet in de overeenkomst staat).","Behoud van je WW-uitkering, mits de overeenkomst neutraal is opgesteld en het initiatief bij de werkgever ligt.","Minimaal de transitievergoeding, maar bij een sociaal plan vaak meer.","Ruimte om te onderhandelen over vergoeding, vrijstelling van werk, outplacement en de einddatum."] },
      { h:"Wat je nú kunt doen", p:"Teken niets onder druk. Laat je overeenkomst controleren voordat de bedenktermijn verstrijkt, en vergelijk het aanbod met het sociaal plan en de wettelijke bodem. Eén gesprek met een specialist kan duizenden euro's en je WW-zekerheid schelen." }
    ],
    faq:[
      { q:"Moet ik akkoord gaan omdat het een reorganisatie is?", a:"Nee. Ook bij een reorganisatie is een vaststellingsovereenkomst een voorstel waarover je mag onderhandelen. Je hoeft het eerste aanbod niet te accepteren." }
    ] },
  { slug:"asml-reorganisatie-wat-betekent-dit", cat:"Bedrijfsnieuws", date:"2026-06-20", read:5,
    title:"ASML schrapt banen: wat betekent de reorganisatie voor jou?",
    h1:"ASML schrapt banen: wat betekent dit voor jou?",
    desc:"ASML kondigde eind januari 2026 een reorganisatie aan met circa 1.400 banen minder in Nederland. Wat betekent het sociaal plan voor jouw vaststellingsovereenkomst?",
    intro:"Voor de Brainport-regio is ASML meer dan een werkgever: het is de motor onder duizenden banen bij toeleveranciers. De aangekondigde reorganisatie raakt daarom niet alleen ASML zelf.",
    blocks:[
      { h:"Wat er speelt", p:"ASML kondigde eind januari 2026 een reorganisatie aan waarbij circa 1.400 functies in Nederland verdwijnen. Na overleg met de vakbonden ligt er inmiddels een sociaal plan met een looptijd van twee jaar, ingegaan op 1 juni 2026. Zo'n sociaal plan bepaalt vaak een vergoeding boven de wettelijke transitievergoeding." },
      { h:"Waarom het sociaal plan cruciaal is", p:"Ken je het sociaal plan niet, dan onderhandel je in het duister. Het legt bijvoorbeeld vast welke vergoeding, welke begeleiding naar ander werk en welke termijnen gelden. Controleer altijd of jouw persoonlijke aanbod klopt met wat het sociaal plan belooft." },
      { h:"Ook toeleveranciers voelen het", p:"Rond Eindhoven en Veldhoven hangt een heel ecosysteem van hightech-toeleveranciers aan ASML. Werk je daar en verandert jouw situatie mee, dan gelden dezelfde rechten: bedenktermijn, WW-bescherming en onderhandelingsruimte." },
      { h:"Wat je kunt doen", p:"Laat je overeenkomst naast het sociaal plan leggen voordat je tekent. Vaak zit er meer in dan het eerste voorstel, zeker bij een grote, goed geregelde reorganisatie." }
    ] },
  { slug:"transitievergoeding-2026", cat:"Geld & vergoeding", date:"2026-06-10", read:5,
    title:"Transitievergoeding in 2026: hoe het écht werkt",
    h1:"Transitievergoeding in 2026: hoe het écht werkt",
    desc:"Hoe bereken je je transitievergoeding in 2026, wat is het maximum en waarom is het een bodem en geen plafond? Een heldere uitleg met rekenvoorbeeld.",
    intro:"De transitievergoeding is het bedrag waar je bij ontslag in beginsel recht op hebt. Belangrijk om te weten: het is het minimum, niet het maximum.",
    blocks:[
      { h:"De berekening", p:"De transitievergoeding bedraagt een derde maandsalaris per gewerkt jaar, naar rato voor de resterende maanden en dagen. Onder maandsalaris valt niet alleen je bruto loon, maar ook vakantiegeld en vaste toeslagen zoals een dertiende maand of ploegentoeslag." },
      { h:"Het maximum in 2026", p:"In 2026 is de transitievergoeding maximaal € 102.000 bruto. Verdien je meer dan dat op jaarbasis, dan is je maximum gelijk aan één bruto jaarsalaris." },
      { h:"Een bodem, geen plafond", p:"De transitievergoeding is wettelijk het minimum. Bij een vaststellingsovereenkomst, en zeker bij een reorganisatie met sociaal plan, valt er vaak meer te onderhandelen: een hogere vergoeding, vrijstelling van werk met behoud van salaris, of een bijdrage aan omscholing." },
      { h:"Rekenvoorbeeld", p:"Verdien je € 4.000 bruto per maand (inclusief vakantiegeld) en werk je tien jaar in dienst, dan is je transitievergoeding ongeveer € 13.300. Krijg je minder aangeboden, dan ligt je aanbod onder de wettelijke bodem en valt er vrijwel zeker meer te halen." }
    ],
    faq:[
      { q:"Telt mijn vakantiegeld mee?", a:"Ja. Vakantiegeld en vaste toeslagen tellen mee bij het bepalen van je maandsalaris voor de transitievergoeding." }
    ] },
  { slug:"boventallig-verklaard-5-stappen", cat:"Reorganisatie", date:"2026-05-28", read:4,
    title:"Boventallig verklaard? Dit zijn je eerste 5 stappen",
    h1:"Boventallig verklaard? Dit zijn je eerste 5 stappen",
    desc:"Net te horen gekregen dat je boventallig bent? Blijf rustig en doorloop deze vijf stappen voordat je iets tekent.",
    intro:"Het bericht dat je functie vervalt komt bijna altijd hard aan. Toch is het belangrijkste wat je nu kunt doen: even niets tekenen en het hoofd koel houden.",
    blocks:[
      { h:"Stap 1 — Teken nog niets", p:"Een boventalligverklaring is geen ontslag. Zet geen handtekening en ga geen mondelinge toezeggingen aan. Alles wat je tekent, telt." },
      { h:"Stap 2 — Vraag het sociaal plan op", p:"Bij een reorganisatie is er vaak een sociaal plan. Vraag het op en lees welke vergoeding, begeleiding en termijnen erin staan. Dit is je ijkpunt." },
      { h:"Stap 3 — Controleer de afspiegeling", p:"Ga na of je werkgever de juiste functiegroep en het afspiegelingsbeginsel correct heeft toegepast. Fouten hierin geven je een sterkere positie." },
      { h:"Stap 4 — Bereken je bodem", p:"Bereken je transitievergoeding, zodat je weet wat het wettelijke minimum is. Vergelijk dat met het aanbod." },
      { h:"Stap 5 — Laat het checken", p:"Laat de overeenkomst controleren binnen je bedenktermijn. De kosten hiervoor worden vaak door de werkgever vergoed." }
    ] },
  { slug:"ww-veilig-bij-vso", cat:"WW & zekerheid", date:"2026-05-15", read:5,
    title:"Zo houd je je WW veilig bij een vaststellingsovereenkomst",
    h1:"Zo houd je je WW veilig bij een VSO",
    desc:"Een verkeerd geformuleerde vaststellingsovereenkomst kan je WW-uitkering kosten. Dit zijn de voorwaarden waar je op moet letten.",
    intro:"Een goede vergoeding is mooi, maar zonder WW-zekerheid kan een vaststellingsovereenkomst je duur komen te staan. Gelukkig is je WW veilig te stellen, mits de tekst klopt.",
    blocks:[
      { h:"Het initiatief moet bij de werkgever liggen", p:"Uit de overeenkomst moet duidelijk blijken dat het ontslag op initiatief van de werkgever is genomen. Neem je zelf ontslag, dan vervalt in de regel je recht op WW." },
      { h:"Neutrale, niet-verwijtbare gronden", p:"De reden moet neutraal zijn: bedrijfseconomisch of een verstoorde arbeidsrelatie zonder verwijt aan jou. Staat er een dringende reden of een verwijt in, dan brengt dat je WW in gevaar." },
      { h:"Respecteer de fictieve opzegtermijn", p:"De einddatum moet rekening houden met de opzegtermijn die zou gelden. Wordt die niet gerespecteerd, dan kan het UWV je WW een periode uitstellen, waardoor er een gat in je inkomen valt." },
      { h:"Laat het controleren", p:"Deze voorwaarden lijken klein, maar één verkeerde formulering kan maanden WW kosten. Laat de tekst daarom altijd checken voordat je tekent." }
    ],
    faq:[
      { q:"Kan ik mijn WW kwijtraken door een VSO te tekenen?", a:"Ja, als de overeenkomst verkeerd is opgesteld. Met neutrale gronden, het initiatief bij de werkgever en een correcte einddatum blijft je WW in de regel veilig." }
    ] }
];

module.exports = { WA, companies, cities, scenarios, companyNews, articles };